### ISSUE TITLE
Can not clear the search field in the Everything.me screen.

### ISSUE THREAD

**Issue by JosiahOne** [mozilla/r2d2b2g#324] opened 2013-02-22 15:41 UTC
Quite consistently, when you search and press enter in the Everything.me search field it does not allow you to clear the search field with the (x) button.

I can not be sure this is a simulator issue or part of the Firefox OS, but it should be investigated.

**Comment by nickdesaulniers** [comment] 2013-02-25 21:06
Verified this is occurring in the simulator and not on device.
It probably has to do with using touch events as opposed to click events.

**Comment by mykmelez** [comment] 2013-03-29 18:17
I see this too. As @nickdesaulniers noted, it's probably caused by lack of support for touch events, which is #166. (It might also be a bug in everything.me, but then that is best reported in the B2G issue tracker.) Closing as a duplicate of #166, but please reopen if it still doesn't work after we resolve that issue!

**Closed as completed by mykmelez** 2013-03-29 18:17 UTC
Labels: bug
