### ISSUE TITLE
Cannot rotate when started within an app

### ISSUE THREAD

**Issue by nickdesaulniers** [mozilla/r2d2b2g#346] opened 2013-03-06 18:46 UTC
If you start the simulator into an app, then rotation is disabled and you need to go home, then back to the app to rotate it.  By start the simulator into an app I mean from the app list select run or update.

STR:
1. Open Firefox OS Simulator
2. Click on update (for an existing app, previously installed)
3. The Simulator should start with that app open, click rotate button

Expected:
Rotate button is enabled
Prosthesis shell should rotate

Actual:
Rotate button is disabled
Prosthesis shell does not rotate

Sounds like we always assume we will boot to home screen, which should lock the orientation, but we provide other means of starting the simulator without booting to the home screen.

**Comment by mykmelez** [comment] 2013-03-06 18:53
@rpl

**Comment by rpl** [comment] 2013-03-06 19:46
@mykmelez @nickdesaulniers I'm looking into this:
it seems related to run an app during the b2g-desktop starting up process,
because it works correctly if b2g-desktop instance is already running.

**Comment by mykmelez** [comment] 2013-04-10 00:08
@rpl: Have you made any progress looking into this?

**Comment by rpl** [comment] 2013-04-10 12:14
@mykmelez it should be fixed now (it was one of the "simulated screen
refactoring" motivations)

I'll check again this use case to be sure.

**Comment by nickdesaulniers** [comment] 2013-04-18 22:56
Not fixed as of 3.0pre6 :(

**Comment by rpl** [comment] 2013-04-19 14:24
This is really unfortunate :-(
If I correctly understand the problem, this is not happening on my system anymore,
but I've tried on a mostly empty application with an orientation attribute in the manifest.

@nickdesaulniers can u send me the app you're using to test this issue and/or a screencast
so I can better understand the issue and how to reproduce it?

**Comment by mykmelez** [comment] 2013-04-19 16:18
I'm unable to reproduce. My steps are:
- add the Mykzilla app: http://mykzilla.org/app/manifest.webapp
- stop the Simulator
- press the Mykzilla app's Run button in the Dashboard
- press the Rotate button in the Simulator

When I do that, the Simulator changes its orientation as expected. I'm testing with 3.0pre6 on Mac.

@nickdesaulniers Which app are you using to test, and on which OS?

**Comment by nickdesaulniers** [comment] 2013-04-19 17:05
Oh so it is working correctly.  The app I was testing with had the values in the manifest:
"orientation": "portrait-primary"

**Comment by mykmelez** [comment] 2013-04-19 17:16
> Oh so it is working correctly. The app I was testing with had the values in the manifest:
> "orientation": "portrait-primary"

Yup, that locks the orientation, so it's expected that the orientation won't change. However, it isn't very clear why it doesn't. So there's more work to do here on the user experience. Ideas off the top of my head:
- disable the button when it isn't possible to change the orientation
- add a tooltip to the button when it's disabled that explains why the orientation can't be changed
- make the button rotate the viewport regardless of whether or not the orientation changes, so apps that lock the orientation appear sideways when the button is pressed (making a clearer distinction between physical "rotation", which is something that the user of a real device can always control, and which is what we should really be simulating when the user presses that button; and virtual "orientation", which is something that the app and/or OS controls)

**Comment by mykmelez** [comment] 2013-04-19 21:08
Mmm, let's actually open new issues for the various enhancements. The better to track discrete units of work!

**Closed as completed by mykmelez** 2013-04-19 21:08 UTC
Labels: bug, P2
