### ISSUE TITLE
Address Bar not showing after visiting some websites

### ISSUE THREAD

**Issue by ghost** [mozilla/r2d2b2g#294] opened 2013-02-06 04:59 UTC
Starting the browser works fine, until loading some websites which seem to hide the URL Bar. This renders the browser basically unusable.

**Comment by nickdesaulniers** [comment] 2013-03-07 23:01
@flakefrost , hey thanks for pointing this out.  Helping us track down issues is a great start to contributing!  Unfortunately I need help tracking this down, as I have not been able to reproduce.  Can you please update to the latest version of the simulator (3.0pre2), and reverify this issue, then post back here if you're still experiencing this issue, and if so what platform you are on.  That would help us track down this bug faster.  Thanks!

**Comment by mykmelez** [comment] 2013-03-29 17:59
Here are links to the latest preview build: [Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), and [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi).

I can't reproduce this either, so I'm going to close the issue, but please reopen it if you can still reproduce the problem on the latest preview build!

**Closed as completed by mykmelez** 2013-03-29 17:59 UTC
Labels: info-needed
