### ISSUE TITLE
Simulator not working properly on Windows 8 Firefox?And how to lunch Marketplace ?

### ISSUE THREAD

**Issue by ghost** [mozilla/r2d2b2g#106] opened 2012-11-16 15:57 UTC
i am using windows 8 i installed Firefox OS simulator at first it was OK  up-to 2 to 5 times then after it stopped working and not even launching ..effort was good by Mozilla people to test and submit feedback using testing but i cannot launch marketplace in OS to check any apps and try it fro testing .and kindly fix the simulator error i like the OS really very good ..

**Comment by mykmelez** [comment] 2012-11-16 23:34
Sorry to hear about your problem! We've noticed that sometimes a Simulator process stays running after the Manager tab thinks it has ended and gets stuck; then, when you try to start the Simulator from the Manager, it doesn't start, because it can't get access to its configuration files.

So you might try looking in Task Manager for an existing _b2g.exe_ process or _plugin-container.exe_ process to end (although the latter could belong to Firefox, so be careful which processes you end!). Alternately, restart your computer, which will have the same effect!

**Comment by mykmelez** [comment] 2012-11-26 16:26
Were you able to launch the simulator after taking the steps I recommended?

**Comment by mykmelez** [comment] 2012-12-27 20:53
Closing due to lack of additional information. Please reopen if you can reproduce the problem and provide additional information about it!

**Closed as completed by mykmelez** 2012-12-27 20:53 UTC
