### ISSUE TITLE
Browser is not working.

### ISSUE THREAD

**Issue by sku009** [mozilla/r2d2b2g#233] opened 2012-12-25 13:16 UTC
simulator firefox browser is not showing site content

**Comment by mykmelez** [comment] 2012-12-27 22:17
Hello, thanks for reporting this problem! Unfortunately, you haven't given us enough information to diagnose it. Which site did you try to load, and do other apps that depend on a network connection (like the Email app) also fail? It would also help to know which version of the Simulator you are using and what operating system you are using it on.

**Comment by mykmelez** [comment] 2012-12-27 22:19
@sku009 Given that you also filed issue #234, I suspect your problem is that your installation of the Simulator doesn't have network connectivity. Does your computer in general have network connectivity when you are using the Simulator? And does your network require you to configure a proxy server by any chance?

**Comment by Smalllily** [comment] 2012-12-28 08:40
I also encountered this issue. I'm sure my PC was in correct network since my Firefox browser can work normally.
But browser on simulator failed to open any site..

**Comment by Smalllily** [comment] 2012-12-28 09:18
The issue has been resolved, the root cause is the proxy config for ie. After I removed the proxy from ie setting, the browser on simulator starts working!!

**Comment by nickdesaulniers** [comment] 2013-03-07 23:11
Is this still an issue?  Maybe a different issue on proxy settings is necessary?

**Comment by mykmelez** [comment] 2013-03-29 17:28
Proxy settings is issue #130. Closing this as we don't have needed info from the original reporter, and the issue has been resolved for the second reporter.

**Closed as completed by mykmelez** 2013-03-29 17:28 UTC
Labels: info-needed
