### ISSUE TITLE
reported geolocation doesn't change immediately after being changed by user

### ISSUE THREAD

**Issue by mykmelez** [mozilla/r2d2b2g#519] opened 2013-05-13 23:23 UTC
The geolocation reported to apps by the geolocation simulation doesn't always change immediately after being changed by the user. Sometimes apps that check the location right after the user changes it still see the old location for some period of time.

I've seen this with my [Mykzilla test app](http://www.mykzilla.org/app/), and I've heard of it happening to other users. In fact it seems to be quite common. Which makes it hard to debug geolocation use in apps, since developers can't reliably test the effect of a location change on their apps.

@nickdesaulniers Do you have any ideas about what might be going on here?

**Comment by nickdesaulniers** [comment] 2013-05-13 23:37
Because this isn't hooked up to watch position, there is a [timer that takes a second to update](https://github.com/mozilla/r2d2b2g/blob/96bbe42e665f91401784e1d484c6e6139db4c473/prosthesis/components/FakeGeolocationProvider.js#L85) the coordinates.  I think this is a duplicate of #470 .

**Comment by nickdesaulniers** [comment] 2013-05-22 23:07
fixed in #544

**Closed as completed by nickdesaulniers** 2013-05-22 23:07 UTC
Labels: bug, P1
