### ISSUE TITLE
simulator closed with error 

### ISSUE THREAD

**Issue by xTaZe** [mozilla/r2d2b2g#397] opened 2013-03-27 00:24 UTC
when i open the simulator , it close after 5 seconds, when i open the console it shows there errors ! 
what should i do ?!
i use Win 7 , FireFox 19.0.2 , same problem with Firefox Simulator 2.0 and 3.0pre! 
![FirefoxOs](https://f.cloud.github.com/assets/3842372/306244/b35df424-9674-11e2-8d10-8983dc0c1477.png)

**Comment by willicab** [comment] 2013-03-27 00:52
Me too, this is the output in terminal with version 2

willicab@williamcabrera:~/.mozilla/firefox/a007ww2s.default-1364340493206/extensions/r2d2b2g@mozilla.org/resources/r2d2b2g/data/linux/b2g$ ./b2g
ATTENTION: default value of option force_s3tc_enable overridden by environment.
prosthesis:patch RemoteDebugger.start
###################################### forms.js loaded
[AccessFu] INFO attach
###################################### forms.js loaded
prosthesis:processing -dbgport command line option
prosthesis:remote debugger will start on port: null
prosthesis:processing -pbport command line option
prosthesis:pingpack port is: null
XXX FIXME : Got a mozContentEvent: system-message-listener-ready
prosthesis:loading simulator actor definition
prosthesis:sending pingback
XXX FIXME : Got a mozContentEvent: accessibility-screenreader
FTU manifest cannot be found skipping.
###################################### forms.js loaded
creating 1!
Abortado

And version 3

willicab@williamcabrera:~/.mozilla-bak/firefox/a4zhc4m6.default/extensions/r2d2b2g@mozilla.org/resources/r2d2b2g/data/linux/b2g$ ./b2g
ATTENTION: default value of option force_s3tc_enable overridden by environment.
prosthesis:patch RemoteDebugger.start
###################################### forms.js loaded
############################### browserElementPanning.js loaded
######################## BrowserElementChildPreload.js loaded
[AccessFu] INFO attach
###################################### forms.js loaded
############################### browserElementPanning.js loaded
######################## BrowserElementChildPreload.js loaded
SIMULATOR SCREEN COMPONENT LOADING
SIMULATOR SCREEN INIT CALLED
SCREEN: portrait-primary
REQUEST ORIENTATION LOCK: portrait-primary
prosthesis:processing -dbgport command line option
prosthesis:remote debugger will start on port: null
prosthesis:processing -pbport command line option
prosthesis:pingpack port is: null

(b2g:6852): GLib-GObject-WARNING **: /build/buildd-glib2.0_2.33.12+really2.32.4-2-i386-TMMpf5/glib2.0-2.33.12+really2.32.4/./gobject/gsignal.c:3397: signal name `load_complete' is invalid for instance`0xa5009700'
prosthesis:loading simulator actor definition
prosthesis:sending pingback
REQUEST ORIENTATION LOCK: portrait-primary
XXX FIXME : Got a mozContentEvent: system-message-listener-ready
simulator - LOCKSCREEN ENABLED: true
simulator - HOMESCREEN LOCKED: wait for lockscreen.locked 
XXX FIXME : Got a mozContentEvent: accessibility-screenreader
simulator - HOMESCREEN LOCKED: true
REQUEST ORIENTATION LOCK: portrait-primary
simulator - LOCKSCREEN NOT FULLY LOADED. EXCEPTION: TypeError: WindowManager.getAppFrame(...) is null
simulator - HOMESCREEN LOCKED: true
REQUEST ORIENTATION LOCK: portrait-primary
simulator - LOCKSCREEN NOT FULLY LOADED. EXCEPTION: TypeError: WindowManager.getAppFrame(...) is null
simulator - HOMESCREEN LOCKED: true
REQUEST ORIENTATION LOCK: portrait-primary
simulator - LOCKSCREEN NOT FULLY LOADED. EXCEPTION: TypeError: WindowManager.getAppFrame(...) is null
FTU manifest cannot be found skipping.
###################################### forms.js loaded
############################### browserElementPanning.js loaded
######################## BrowserElementChildPreload.js loaded
simulator - HOMESCREEN LOCKED: true
REQUEST ORIENTATION LOCK: portrait-primary

(b2g:6852): GLib-GObject-WARNING **: /build/buildd-glib2.0_2.33.12+really2.32.4-2-i386-TMMpf5/glib2.0-2.33.12+really2.32.4/./gobject/gsignal.c:3397: signal name `load_complete' is invalid for instance`0xa0232be0'
REQUEST ORIENTATION LOCK: portrait-primary
simulator - HOMESCREEN LOCKED: true
REQUEST ORIENTATION LOCK: portrait-primary
Abortado

**Comment by mykmelez** [comment] 2013-03-29 21:37
@xTaZe I think those console messages are unrelated. Try the [latest preview build for Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), and if you still experience the problem, then use about:config to create the preference extensions.r2d2b2g@mozilla.org.sdk.console.logLevel, set it to the integer value 0, disable/reenable the addon, restart the Simulator, and let me know what you see in Firefox's Error Console.

@willicab You're on Linux, so you may be experiencing a different problem. It's hard to tell from that output, though, because you're running b2g directly instead of via the Simulator, and there may be issues with doing that. Try starting Firefox from the command line, then start the Simulator from the Dashboard. The console output may look similar, but at least we can rule out any issues caused by running b2g directly.

**Comment by xTaZe** [comment] 2013-03-29 23:50
when i run the simulator , in the Firefox Error console , it show me : 
![Capture](https://f.cloud.github.com/assets/3842372/319577/7a608cfa-98cb-11e2-920c-15945f74ab5d.PNG)

**Comment by xTaZe** [comment] 2013-03-29 23:53
and  always the same bugs in Simulator's Console !

**Comment by mykmelez** [comment] 2013-03-30 01:10
Thanks for the screenshot! From it, I notice two things:
1. b2g.exe exits with a 0 exit code; i.e. it exits cleanly, it doesn't crash.
2. You're using a version of Windows with a French localization, which means the path to your Firefox profile might contain accented characters (f.e. in your username).

We have a known issue #247 with starting the Simulator from a Firefox profile whose path contains accented characters, so I suspect that issue is the cause of your problem. To see if that's the case, use cmd.exe to create a profile that doesn't contain accented characters and then run Firefox from that path.

For example:

```
mkdir C:\r2d2b2g-profile
"C:\Program Files (x86)\Mozilla Firefox\firefox.exe" -no-remote -profile C:\r2d2b2g-profile
```

(Note: your copy of Firefox might be located at a different location. A Linux version of these commands is described in [this comment on issue #247](https://github.com/mozilla/r2d2b2g/issues/247#issuecomment-13397861).)

Then install the latest preview build of the Simulator in the instance of Firefox you started with the new profile, and see if you still have the problem.

**Comment by xTaZe** [comment] 2013-03-30 15:54
i have executed the exemple ! i have created a new profile ! but always a same problem :/ 
i use a frensh version of Win , and i dont use accented characters !! and always the same problem :/

**Comment by xTaZe** [comment] 2013-03-30 16:43
there some avertissement !
![Sans titre](https://f.cloud.github.com/assets/3842372/320656/f259142e-9958-11e2-87fb-882f5690624d.png)

**Comment by AceFubar** [comment] 2013-04-02 03:39
I have the same problem, Yet no french localization here, something to do with my java script I think
![Simulator OS crash](https://f.cloud.github.com/assets/4032704/326759/9166b630-9b47-11e2-9f6c-052a86b18c8b.png)

**Comment by mykmelez** [comment] 2013-05-03 22:56
@xTaZe and @AceFubar, can you try the latest preview build ([Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), and [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi)) and let me know if you still experience the problem?

**Comment by mykmelez** [comment] 2013-05-13 17:14
Closing this due to lack of needed info, but please reopen if you can still reproduce it!

**Closed as completed by mykmelez** 2013-05-13 17:14 UTC
