### ISSUE TITLE
Built-in-keyboard does not work

### ISSUE THREAD

**Issue by bocajspear1** [mozilla/r2d2b2g#191] opened 2012-12-11 22:13 UTC
When a key on the keyboard is clicked, the entire built-in keyboard disappears and no letter is inserted into the currently selected textbox. 

OS: Windows 7
Firefox 17.0.1
Simulator Version 1.0

**Comment by waldyrious** [comment] 2012-12-12 01:25
I have the same issue. Versions are the same as above, only difference is OS: Xubuntu 12.04

**Comment by mykmelez** [comment] 2012-12-20 19:57
I see this on Mac as well, so it isn't OS-specific. It looks like it's a regression in the version of B2G/Gaia that shipped with Simulator 1.0, as I didn't see it in earlier versions of the Simulator, and I don't see it on my [update-b2g-gaia branch](https://github.com/mykmelez/r2d2b2g/tree/update-b2g-gaia), which is using a newer version of B2G/Gaia.

I'll integrate that branch before we ship 1.1, so this'll be fixed by that update. In the meantime, you can work around the problem by using your computer's physical keyboard to enter text.

**Comment by mykmelez** [comment] 2012-12-27 21:43
I fixed this in the latest preview build ([Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi)).

**Closed as completed by mykmelez** 2012-12-27 21:43 UTC
