### ISSUE TITLE
Websites do not load

### ISSUE THREAD

**Issue by kaimakes** [mozilla/r2d2b2g#289] opened 2013-02-01 20:58 UTC
They just leave a blank scree, but are visible in the menu.
![FirefoxMobileIssue](https://f.cloud.github.com/assets/2728840/119729/0b7a9cc6-6cb2-11e2-833f-1aeb2e1a387f.png)

**Comment by nickdesaulniers** [comment] 2013-02-23 00:06
Can you please verify that you are running simulator v 2.0?
Go to about:addons -> extensions to get the version string.

**Comment by kaimakes** [comment] 2013-02-23 09:43
Yes, ill do that. But i think i have 2.0 anyway.

**Comment by mykmelez** [comment] 2013-03-29 17:56
@kkraku can you reproduce on the latest preview build?

Latest preview build: [Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), and [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi).

**Comment by mykmelez** [comment] 2013-05-03 21:31
Closing this due to lack of needed info. But please do reopen if you can provide that info!

**Closed as completed by mykmelez** 2013-05-03 21:31 UTC
