### ISSUE TITLE
Simulator not starting properly on 12.04 ubuntu. Firefox version 20.0

### ISSUE THREAD

**Issue by ihsaninfiyaz** [mozilla/r2d2b2g#473] opened 2013-04-27 12:58 UTC
I can see the dashboard; when I toggle the button that says Running and Stopping, it changes to running, opens a small window with an animation of three red circles, and then shuts off the window suddenly before it goes too further. The next time I click the button it toggles to running as before, but now it opens the window and closes it in a snap. When I restarted my laptop and ran through the same steps, it didn't even open up the simulator window it just toggled, running and stopping.

**Comment by mykmelez** [comment] 2013-04-27 17:10
Hmm, it sounds like the Simulator is crashing on startup. Which version of the Simulator are you using, and are you using a 32-bit or 64-bit version of Ubuntu?

I don't have an Ubuntu 12.04 installation, but I've tested with a 32-bit 11.10 and a 64-bit 12.10 installation, and the [latest preview build for Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi) seems to work correctly on them. So if you're using the stable release (2.0.1), try installing the preview build, and let me know how it works for you!

**Comment by mykmelez** [comment] 2013-05-13 17:30
Closing due to lack of needed info, but please reopen if you can still reproduce it!

**Comment by ihsaninfiyaz** [comment] 2013-05-14 05:28
Hello there, I'm sorry, I don't remember being alerted about the first reply, but anyway, I'm using the 32bit version of ubuntu, and the Simulator's version is 3.0. After the first time of installing and opening the Simulator, unless I bookmark the page, I can't reopen it again as well.

How would I install the preview build? I got this version off the addon page, the one that pops up if you hold down this combination: Shift+Ctrl+A.

**Comment by mykmelez** [comment] 2013-05-17 17:34
> Hello there, I'm sorry, I don't remember being alerted about the first reply, but anyway, I'm using the 32bit version of ubuntu, and the Simulator's version is 3.0. After the first time of installing and opening the Simulator, unless I bookmark the page, I can't reopen it again as well.

Thanks for getting back to me! That issue with subsequent runs of the Simulator makes it sound like a problem with loading the addon on Firefox startup. What version of Firefox are you using?

> How would I install the preview build? I got this version off the addon page, the one that pops up if you hold down this combination: Shift+Ctrl+A.

You can install the preview build by clicking this link:

https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi

**Comment by ihsaninfiyaz** [comment] 2013-05-20 06:25
No prob. I'm using the latest version of Firefox now, thats 21, but it was on 20 that I tried the simulator.

Let me try the preview build and let you know asap.

**Comment by ihsaninfiyaz** [comment] 2013-05-20 07:23
Hi, I can't seem to be able to open it once installed. How should I open it? The previous install, not the preview, it opened it as well automatically. I couldn't open it again though, but this one doesn't even open after the installation.

Thanks for any help in advance!

**Comment by mykmelez** [comment] 2013-05-20 17:15
You should be able to open the Simulator's Dashboard by going to Tools > Web Developer > Firefox OS Simulator.

**Comment by ihsaninfiyaz** [comment] 2013-05-21 06:13
Cool, I got it opened, but unfortunately it's the same story. Here's a screenshot of what's happening JUST before it crashes or closes rather. Its got a few errors (the error console) that you might want to check out as well.
![screenshot from 2013-05-21 11 37 10](https://f.cloud.github.com/assets/4272359/540125/758549c4-c1dd-11e2-8700-ab946a2c69f2.png)

**Comment by jandendolder** [comment] 2013-06-20 10:36
It looks like I have the same issue. I am on ubuntu 12.04 i386. simulator also crashes with the last error message "unknown property '-moz-align-self'. Declaration dropped". Before it crashes the simulator window appears for a few seconds. Oh and if it is of interest I was running on laptop with a ... dead battery. After I made sure the battery was charging the simulator started as expected. Thanks.

**Comment by mykmelez** [comment] 2013-06-20 16:03
@BravoI Are you running the Simulator on a laptop that doesn't have a battery by any chance?

**Comment by ihsaninfiyaz** [comment] 2013-06-20 16:14
@mykmelez Actually, yes, my laptop's battery doesn't stay a second on if the power is cut off. It's dead. (fullstop). Anyway, I switched to Chrome for a while and I'm not using Firefox anymore except for web development and stuff. But please don't close off this topic as it might help others who might have the same issue maybe..

**Comment by mykmelez** [comment] 2013-06-20 16:16
@BravoI It sounds like this is a duplicate of #536, so I thought I'd close this one and direct folks to that one. Otherwise, conversation will get split between the two issues, which makes it harder to collaborate on a fix. Does that seem like a reasonable plan?

**Comment by ihsaninfiyaz** [comment] 2013-06-20 16:18
Yes, it certainly does seem reasonable. Please do that.

**Comment by mykmelez** [comment] 2013-06-20 16:21
Cool, closing this one then!

Folks: if you're experiencing this issue, check out #536 to find out about progress toward resolving it!

**Closed as completed by mykmelez** 2013-06-20 16:21 UTC
Labels: info-needed
