### ISSUE TITLE
FIrefox OS Simulator crashes when trying to open notification bar

### ISSUE THREAD

**Issue by swarnava** [mozilla/r2d2b2g#168] opened 2012-12-01 10:48 UTC
when changing menu left to right and then try to open notification bar, it crashes. i sent crashreport but couldnot locate where is it, is it stay on about:crashes section?

**Comment by mykmelez** [comment] 2012-12-04 18:50
Hi @swarnava, I'm not quite sure what you mean by "changing menu left to right". Can you explain further?

Unfortunately, crash reports for B2G are not yet very useful because of [bug 785698](https://bugzilla.mozilla.org/show_bug.cgi?id=785698). If you can explain the specific steps to reproduce the crash, and I can reproduce it on my system, then I may be able to generate a stack trace by using a debug build of B2G.

It would also be useful to know what operating system you're using and which version of the Simulator you have installed!

**Comment by mykmelez** [comment] 2012-12-20 20:17
Closing due to lack of info about the problem. Please reopen if you can provide additional information!

**Closed as completed by mykmelez** 2012-12-20 20:17 UTC
