### ISSUE TITLE
Activity (mozSetMessageHandler, etc)

### ISSUE THREAD

**Issue by Jaxo** [mozilla/r2d2b2g#392] opened 2013-03-25 16:53 UTC
Not sure if these are bugs, or working as designed, b/c I didn't found much doc..
So I'm reporting the facts, as I learned from my tests.

1) "inline activity" can not open "browser tabs" (e.g.: window.open), 
    "window activity" can
2) posting back when a "window activity" is done does not wake up the "issuer" 
    posting back from an "inline activity" do return to the caller
3) in no case the activity exits: once it has been started, it stays there forever.

The last point could be problematic: you can not use the same activity as a standalone one, and as an activated one.  When you start the stand-alone, it goes to the activated one.

[I realize that this description is not crystal clear.  Don't hesitate for more details.]

**Comment by mykmelez** [comment] 2013-03-29 21:23
I'm not very familiar with the implementation of web activities in B2G/Gaia. This behavior might be intentional, but it could also be due to bugs in B2G/Gaia, or it could be the result of bugs in Simulator. We'll need someone who knows more about web activities to dig into the problems here. Perhaps @digitarald or @nickdesaulniers.

**Comment by digitarald** [comment] 2013-04-01 17:11
Do you see the same problems with the activities started from the Boilerplate [1](https://github.com/robnyman/Firefox-OS-Boilerplate-App) app?

**Comment by mykmelez** [comment] 2013-05-13 17:13
Closing this due to lack of needed info, but please reopen it if you can still reproduce!

**Closed as completed by mykmelez** 2013-05-13 17:13 UTC
