### ISSUE TITLE
Simulator crashes on startup when battery absent on Linux

### ISSUE THREAD

**Issue by Bonstra** [mozilla/r2d2b2g#536] opened 2013-05-18 14:08 UTC
When I attempt to start the simulator (4.0pre2) on my ArchLinux x86_64 laptop with Firefox 21, the simulator window appears, shows the "based on mozilla technology" image, and immediately shutdowns without showing the dashboard (it shows the animations with the three circles, and the window closes).

However, with almost the same setup, the simulator runs fine on my desktop computer in my office. So I went through some investigation and reinstalled my system package after package (it needed some spring cleaning anyway :-) ) until I could spot the one responsible for the problem.
With a system having only the bare minimum to run Firefox, the simulator started and was running fine. However, as soon as I installed the 'upower' package, the issue appeared again.
Upower is responsible for monitoring AC and battery power, among other things. But as my laptop has no battery present inside the slot, upower always reports 0% remaining battery capacity (while still properly reporting the battery as not present) which, I think, is very likely to be the reason why the simulator shuts down.

A workaround for this bug is to disable the battery API (changing the "dom.battery.enabled" to false in greprefs.js worked for me).

A way to fix the bug would be to always report 100% battery capacity when no battery is actually _present_.

One other possible enhancement would be to let the user set the battery capacity value the same way as it can set the GPS coordinates. It would be easier to test applications reacting on battery level without having to wait for your laptop battery to discharge (if you have a laptop and a battery that is).

Hope that helped.

**Comment by mykmelez** [comment] 2013-05-20 17:03
Hi @Bonstra, thanks for reporting this problem! The Simulator doesn't actually have nightly builds, so I wonder if perhaps you are using a nightly build of B2G Desktop. Can you provide the link from which you downloaded the software you're using?

Regardless, of course the software shouldn't crash (and the Simulator should let you simulate battery capacity as well as battery presence/absence). I just want to make sure this issue is reported in the best place.

**Comment by Bonstra** [comment] 2013-05-20 17:41
I got the Firefox OS Simulator from this URL : https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi
The extension details page reads version 4.0pre2.

**Comment by mykmelez** [comment] 2013-05-20 17:48
Ah, ok, you're using the Simulator itself rather than a nightly build of B2G Desktop.

Hmm, I wonder if this is #268. Can you try executing `xhost +` before starting the Simulator?

**Comment by Bonstra** [comment] 2013-05-20 18:15
I first ran the simulator without executing `xhost +`, closed Firefox, executed the `xhost +` command, and ran the simulator again.
I saw no difference between the two runs. The messages in the terminal are the same.

Unlike issue #268, the simulator window appeared for a few seconds, after which it closed. Also, I do not get the "No protocol specified" and "cannot open display" messages.

**Comment by ihsaninfiyaz** [comment] 2013-05-21 06:46
I'm having the same problem as this, AND for your information my laptop's got a battery that's practically dead permanently. https://github.com/mozilla/r2d2b2g/issues/473 - That's the link to the issue, and btw, I formatted the laptop so my firefox's clean except for a few addons like download helper, colorzilla, developer toolbar, etc...
The coincidences:
Your laptop             |          My laptop
ArchLinux x86_64.     |     Ubuntu 12.04 - 32bit
Firefox 21.             |            Firefox 20 then 21
No battery.               |          Have battery, but completely dead.
Simulator version 4.    |     Simulator version 3.

I'll try playing about with the greprefs.js file see what happens.

PS: Where should I look for this file? I tried the /etc/firefox but couldn't find it.

**Comment by Bonstra** [comment] 2013-05-21 11:44
For Linux 32 bit, you'll find the file at this location.
`~/.mozilla/firefox/some_random_string.default/extensions/r2d2b2g@mozilla.org/resources/r2d2b2g/data/linux/b2g/greprefs.js`

**Comment by ihsaninfiyaz** [comment] 2013-05-21 12:19
Thanks for the link, unfortunately the work around didn't work too well. Actually, it didn't open the simulator afterwards.

**Comment by Bonstra** [comment] 2013-05-21 13:45
Try closing all Firefox instances, restart it from a terminal and post the messages you get after starting the simulator.

**Comment by ochameau** [comment] 2013-05-28 10:16
I tried to reproduce it without success on Windows. I'll give it a try on linux.

**Comment by mykmelez** [comment] 2013-06-10 23:09
@ochameau did you have a chance to try it on Linux?

**Comment by mykmelez** [comment] 2013-06-10 23:15
@bkase you have an ArchLinux installation, although I think it's in a VM, which might not be susceptible to this problem. Any chance you can try to reproduce it on that installation?

**Comment by bkase** [comment] 2013-06-11 00:59
According to a bunch of Google-ing, it doesn't seem like it's possible to emulate an unplugged battery from VMWare unless the battery of the host machine is also unplugged. It doesn't look like you're supposed to remove the battery from this MacBook either-- the back is screwed on.

**Comment by nickdesaulniers** [comment] 2013-06-11 16:31
When I read the title I thought it was the craziest thing I've ever heard, but it's totally plausible.  The simulator uses data from the host OS.  For example, open the music app and it will find music local to your computer.  That's probably a privacy policy violation.  Anyways, try disconnecting your power cable on your laptop while the simulator is running.  It looks like the battery status updates around once every 5 seconds.  You'll notice the battery indicator change from being plugged in vs not.  So now if you're using a linux distro without any kind of battery interface, it's probably b2g itself that is crashing; my guess is that they don't handle the case where there are no drivers to interface with the battery to get information such as estimated lifetime or plugged in.

**Comment by mykmelez** [comment] 2013-06-11 17:07
I have a Windows laptop with a removable battery VMware Workstation that I can use to try to reproduce this later this week.

**Comment by ochameau** [comment] 2013-06-12 15:10
I've tried to reproduce it on Ubuntu VM without success, the battery was always 100% charged no matter if the battery was unplugged or almost empty.

**Comment by bkase** [comment] 2013-06-12 22:44
@ochameau Do you have VMWare Fusion? You have to enable passing power status through to the VM.
Check: `Settings -> Advanced -> Pass power status to VM`

**Comment by ochameau** [comment] 2013-06-13 06:59
Yes, I toggled this setting in VMWare player (on windows)

**Comment by mykmelez** [comment] 2013-06-13 20:55
I can reproduce this on my ThinkPad X220 when the battery is absent. I'm testing in an Ubuntu 12.04 LTS VM running in VMware Workstation 9.0.2 on a Windows 7 host OS. The Simulator reports that b2g quit with a 0 exit code, however, so this seems less like a crash than an intentional shutdown. Perhaps something in B2G/Gaia interprets the absence of the battery as a sign that the battery level is 0% (and thus critically low), so it shuts itself down to preserve state?

**Comment by mykmelez** [comment] 2013-06-21 00:20
On startup, the system app checks the battery level and immediately shuts down if the battery is drained:

https://github.com/mozilla-b2g/gaia/blob/f2930cf440e0c8c21b48f7b0b01fac48b941e3fc/apps/system/js/battery_manager.js#L23-L39

It also does this whenever the level changes:

https://github.com/mozilla-b2g/gaia/blob/f2930cf440e0c8c21b48f7b0b01fac48b941e3fc/apps/system/js/battery_manager.js#L63-L68

It seems like the app should shut down only if the battery is drained and the phone isn't charging, so folks with drained batteries can use their phones while recharging their batteries.  Which we should pursue as an upstream fix (provided this isn't intentional behavior).

In the meantime, I'm looking for a workaround. There's a dom.battery.enabled pref that seems like it should enable/disable the navigator.battery API, but it doesn't do that in my tests. Alternately, it might be possible to override navigator.battery with a custom component.

But unfortunately I can no longer reproduce this in my Ubuntu VM! Instead, the Simulator seems to think the battery is present and 100% charged, even though I have physically removed it from the machine. Perhaps Ubuntu landed a fix in an OS update that I recently applied? Is there anyone who can confirm that the problem still occurs for them on Ubuntu 12.04 with all updates applied?

Some more refs:
- https://developer.mozilla.org/en-US/docs/Web/API/window.navigator.battery
- https://developer.mozilla.org/en-US/docs/WebAPI/Battery_Status
- https://developer.mozilla.org/en-US/docs/Web/API/BatteryManager

**Comment by mykmelez** [comment] 2013-06-21 06:00
I figured out how to reproduce it: boot the Ubuntu VM with the battery installed, then remove it after the OS is booted. Apparently the VM determines whether or not to report battery state at boot time (which I read somewhere, perhaps in a Launchpad bug, although I can't find it now).

In any case, now that I can reproduce it consistently, I can experiment with fixes, one of which I'll submit a pull request for shortly.

**Closed as completed** 2013-06-27 16:22 UTC
Labels: bug
