### ISSUE TITLE
Keyboard

### ISSUE THREAD

**Issue by vitorhugomattos** [mozilla/r2d2b2g#252] opened 2013-01-11 19:08 UTC
The keyboard comes open, but clicking on any button, it closes. Using Windows 8, Firefox 18.0 and Firefox OS Simulator 1.1pre1
![Screenshot_3](https://f.cloud.github.com/assets/2721565/60784/3a52b790-5c22-11e2-80f7-7d084bef4611.png)

**Comment by mrfett** [comment] 2013-01-24 18:11
I experience the same behavior in Firefox 18.0.1 in Windows 7 64bit with Firefox OS Simulator 1.0.

**Comment by valenting** [comment] 2013-01-26 15:34
Same here: Windows 7 64bit / Firefox 21a1
Also reproducible in Firefox 21a1 on Ubuntu 12.10

Typing with the hardware keyboard works, but using the mouse to press the onscreen keys doesn't.

**Comment by mykmelez** [comment] 2013-01-28 19:08
I can't reproduce this on the latest preview release (2.0pre5). Can you still reproduce it?

Latest preview release: [Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), and [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi).

**Comment by valenting** [comment] 2013-01-28 19:46
Indeed, it appears to be fixed in 2.0pre5

**Comment by mykmelez** [comment] 2013-01-28 21:03
Awesome, thanks for confirming the fix!

**Closed as completed by mykmelez** 2013-01-28 21:03 UTC
