### ISSUE TITLE
Emulator Crash when website try to download an image on the device 

### ISSUE THREAD

**Issue by mkody** [mozilla/r2d2b2g#537] opened 2013-05-18 15:20 UTC
Hello,

I'm using the lastest development version from the Firefox OS addon on Mac OS 10.8.2 with Firefox beta 22.0. 
When I've tried to click on "View Full Size" on my Facebook profile picture (m.facebook.com), it open a tab, close it after some seconds and B2G.app crash. I think Facebook is making us download the picture, which is possibly not available yet for B2G?

**Comment by mykmelez** [comment] 2013-05-20 16:58
Hi @MKody, thanks for reporting the problem! I see it too, and it isn't clear why it's happening, but B2G shouldn't crash, even if it doesn't support some web platform feature that a webapp tries to use.

Here are my steps to reproduce:
1. start browser app;
2. go to m.facebook.com;
3. sign in;
4. tap menu button in top-left corner;
5. tap own name in menu;
6. tap picture in profile;
7. tap View Full Size link.

Expected Results: I see a full-size version of my profile pic.
Actual Results: the Simulator crashes.

The [B2G Desktop build for the b2g18 branch](https://ftp.mozilla.org/pub/mozilla.org/b2g/nightly/latest-mozilla-b2g18/b2g-18.0.multi.mac64.dmg) also crashes, so it looks like this is a bug in the Simulator's B2G component. But the [B2G Desktop build for the central branch](https://ftp.mozilla.org/pub/mozilla.org/b2g/nightly/latest-mozilla-central/b2g-24.0a1.multi.mac64.dmg) prompts me to open an image in a desktop application, so it looks like this bug has been fixed in central, but the fix wasn't backported to b2g18.

We plan to move to central builds eventually, although it isn't clear when. And that'll resolve this bug. Although it'll introduce the problem that prompting the user to open an image in a desktop application doesn't simulate the experience that users will have on a device.

In the meantime, it probably isn't worth pursuing this bug, as the chance of getting a fix for it onto the b2g18 branch seems slim. But if it's important to the webapp development you're doing, then you could try reporting it in the [Boot2Gecko issue tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Boot2Gecko).

cc: @ochameau so he's aware of the behavior of the central build, which we'll have to override in order to simulate download of an image on a device.

FWIW, note that my FxOS test device opens a tab and then immediately closes it, but it doesn't crash. So this bug is specific to the desktop build of B2G (and possibly to Mac in particular; I haven't tested on other desktop OSes yet).

**Closed as completed by mykmelez** 2013-05-20 16:58 UTC
