### ISSUE TITLE
Fullscreen mode hide Home button

### ISSUE THREAD

**Issue by mathroc** [mozilla/r2d2b2g#309] opened 2013-02-12 10:19 UTC
When an app use the Fullscreen API, the Home button disappear and we can only use the keyboard to escape Fullscreen

**Comment by nickdesaulniers** [comment] 2013-03-07 22:31
@mathroc , do you have a test app we could use to verify real quick?

**Comment by mykmelez** [comment] 2013-03-29 18:11
Issue #198 reports this problem with the Gallery app when you view a picture, although I can't reproduce that anymore. I wonder if this was fixed when we changed a bunch of default style. In any case, closing the issue, but please do reopen if you can still reproduce on the latest preview build!

Latest preview build: [Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), and [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi).

**Closed as completed by mykmelez** 2013-03-29 18:11 UTC
Labels: info-needed
