### ISSUE TITLE
Built in Keyboard not Disappearing after Google Mobile Web Search Query through Firefox Browser

### ISSUE THREAD

**Issue by ghost** [mozilla/r2d2b2g#283] opened 2013-02-01 05:01 UTC
When I search a query on the Mobile Google site through the browser, the search results appear as normal, but the built in Keyboard doesn't hide in order to show the full results. This results with the built in keyboard being in the way of the normal navigation of the Google Search Results. There's plenty of other sites with the same issue, basically anything with a Search function on the page.

There's a temporary work-around: Click the "GO" button instead of simply hitting "ENTER" (Search Results will show and Keyboard will hide). Also try Left-Clicking in the "Enter search or address" bar followed by Left-Clicking a blank spot in the fully loaded Site you're visiting (Keyboard will hide)

**Comment by nickdesaulniers** [comment] 2013-03-07 23:17
I'm sorry but I do not fully understand the problem.  Can you please lay out clearer steps to reproduce?  Thanks!

**Comment by mykmelez** [comment] 2013-03-29 17:50
Closing due to lack of info needed to diagnose the problem. Please reopen if you have such info!

**Closed as completed by mykmelez** 2013-03-29 17:50 UTC
Labels: info-needed
