### ISSUE TITLE
exception on AlarmService.jsm

### ISSUE THREAD

**Issue by stefanostatuti** [mozilla/r2d2b2g#547] opened 2013-05-22 13:05 UTC
Timestamp: 22/05/2013 14:43:15
Error: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIAlarmHalService.setAlarm]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/AlarmService.jsm :: <TOP_LEVEL> :: line 77"  data: no]
Source File: resource://gre/modules/AlarmService.jsm
Line: 77

**Comment by stefanostatuti** [comment] 2013-05-25 16:12
in 4.3 

Timestamp: 25/05/2013 18:01:17
Error: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIAlarmHalService.setAlarm]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/AlarmService.jsm :: <TOP_LEVEL> :: line 92"  data: no]
Source File: resource://gre/modules/AlarmService.jsm
Line: 92

**Comment by mykmelez** [comment] 2013-06-10 19:08
Hi @stefanostatuti, can you provide some more information about the circumstances under which you see this exception? If it is triggered by your code, then it would be useful to see the code that triggers it.

**Comment by stefanostatuti** [comment] 2013-06-11 21:03
ok 
i can regenerate the problem:

Timestamp: 11/06/2013 22:56:39
Error: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIAlarmHalService.setAlarm]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/AlarmService.jsm :: <TOP_LEVEL> :: line 92"  data: no]
Source File: resource://gre/modules/AlarmService.jsm
Line: 92

1 start the simulator & clean ALL the logs
2 open the clock AFTER close it (force the closure)
3 start the calendar
4 watch the log

when restart the simulator receive the same problem

Timestamp: 11/06/2013 22:59:48
Error: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIAlarmHalService.setAlarm]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/AlarmService.jsm :: <TOP_LEVEL> :: line 92"  data: no]
Source File: resource://gre/modules/AlarmService.jsm
Line: 92

**Comment by mykmelez** [comment] 2013-06-17 17:54
@stefanostatuti Thanks for the additional information! Using your steps to reproduce the problem, I was able to reproduce it. However, it isn't clear whether or not it prevents developers from testing their apps on the Simulator. Are you developing an app and having trouble testing it because of this problem?

Note that the Simulator is intended to be a test environment for app developers, and this issue tracker only tracks issues with testing apps. It doesn't track other problems with Firefox OS. That's why I ask about whether or not you are developing an app. It helps me to understand if this is a problem that prevents you from using the Simulator for its intended purpose.

**Comment by stefanostatuti** [comment] 2013-06-17 20:09
No, i start to develop my first app on 21 June (http://www.eventbrite.it/event/6990409503/efblike). now i try only the simulator :D

**Comment by mykmelez** [comment] 2013-07-18 23:36
Since this doesn't prevent you from developing an app, I'm going to close it. But please reopen it if that changes!

**Closed as completed by mykmelez** 2013-07-18 23:36 UTC
