### ISSUE TITLE
Update function on Dashboard cannot work to refresh the app. on local file storage

### ISSUE THREAD

**Issue by RudyLu** [mozilla/r2d2b2g#269] opened 2013-01-26 07:51 UTC
I cannot use [Update] button on the Dashboard to refresh the app after I have made some modifications to the implementation.
# STR
1. Load an app from local file system.
2. Make some modifications to the HTML files of the app
3. Press [Update] button - it will show an banner on simulator that the app is installed
4. relaunch the app. to check

Expected:
   The app has been updated.

Actual:
  It still shows the old state of the app.
## 

Note:
After deleting the offline cache in the Gaia profile, it could work to refresh the app.
However, I think it would be better to resolve this issue for developer to modify and try their app.

Thanks.

**Comment by pedronsouza** [comment] 2013-01-26 16:33
I'm having the exactly same issue here

**Comment by mykmelez** [comment] 2013-01-28 19:53
This might be a duplicate of #66. @digitarald: what do you think?

**Comment by digitarald** [comment] 2013-01-28 21:39
True, #66 should solve that issue. Also seems like the app wasn't killed; which the webapp actor should offer as option when re-installing an app.

**Comment by mykmelez** [comment] 2013-01-28 21:40
Hmm, seems like it should just do it automatically when reinstalling an app, since there's no question at that point: the developer certainly wants to see the new version of the app.

**Comment by mykmelez** [comment] 2013-05-03 22:21
Killing the app was fixed by #314. The rest of this request seems identical to #66, so let's use that issue to track it.

**Closed as completed by mykmelez** 2013-05-03 22:21 UTC
Labels: bug
