### ISSUE TITLE
some problem when i try to delete my apps from the menu

### ISSUE THREAD

**Issue by stefanostatuti** [mozilla/r2d2b2g#565] opened 2013-05-25 16:54 UTC
when i try to delete from menu my apps (long click in app)
![1](https://f.cloud.github.com/assets/4499372/564350/7a61bfe6-c55b-11e2-8e3e-7b8c241f2d97.png)
 i can move my app
![2](https://f.cloud.github.com/assets/4499372/564351/8d685a6e-c55b-11e2-8ece-464e62fa8eae.png)
 but i click in home button(exit from "delete app mode") my app remain undere the clock in dashboard
![3](https://f.cloud.github.com/assets/4499372/564353/99783fb8-c55b-11e2-9bb8-52d29d63b6cc.png)
I can regenerate the problem
![4](https://f.cloud.github.com/assets/4499372/564361/4d8c4954-c55c-11e2-86a5-177c2189e718.png)

W7 ultimate FF 22 simulator version 4.3

**Comment by mykmelez** [comment] 2013-06-10 18:49
I saw this too, but I can't reproduce it in the latest preview build ([Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi)). Can you try that build and let me know if it still happens for you?

**Comment by stefanostatuti** [comment] 2013-06-17 20:19
hi under windows (whit lastest build dev6) i have the same . NOW i try to do a clean install.

**Comment by mykmelez** [comment] 2013-07-18 23:35
Hi @stefanostatuti, did the clean install make any difference? If not, you might try installing the 4.0 release build: https://addons.mozilla.org/en-US/firefox/addon/firefox-os-simulator/

I'm going to close this in the meantime, since I think we've fixed it. But please reopen if you can still reproduce it!

**Closed as completed by mykmelez** 2013-07-18 23:35 UTC
Labels: bug
