### ISSUE TITLE
page jumps up and down after focusing text field in browser 

### ISSUE THREAD

**Issue by CobainLed** [mozilla/r2d2b2g#200] opened 2012-12-12 11:21 UTC
when I select a field to enter text, the screen rises and descends infinitely
this the URL : http://m.facebook.com/login.php?next=http%3A%2F%2Fm.facebook.com%2Fhome.php%3Frefsrc%3Dhttp%253A%252F%252Fm.facebook.com%252Fcheckpoint%252F&refsrc=http%3A%2F%2Fm.facebook.com%2Fcheckpoint%2F&_rdr

**Comment by mykmelez** [comment] 2012-12-12 18:46
Hmm, that sounds problematic! Which field did you select, and in which application, when you saw this?

**Comment by CobainLed** [comment] 2012-12-13 08:35
I log on the site facebook, when I click the login fields or password the screen goes up and decent non-stop

**Comment by mykmelez** [comment] 2012-12-20 20:32
Hmm, I see this too on m.facebook.com, although I don't see it on other sites with text fields.

I just checked a newer version of B2G/Gaia, and it looks like the problem is fixed there, so this appears to be a B2G/Gaia issue that has already been fixed. The fix will make it into the Simulator the next time we update it to a newer version of B2G/Gaia.

**Comment by mykmelez** [comment] 2012-12-27 21:55
This is fixed in the most recent preview builds of the next version of the Simulator ([Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi)).

**Closed as completed by mykmelez** 2012-12-27 21:55 UTC
