### ISSUE TITLE
Simulator from 27-Dec-2012 18:13 doesn't launch app on ubuntu 12.04

### ISSUE THREAD

**Issue by gaffo** [mozilla/r2d2b2g#250] opened 2013-01-05 21:44 UTC
When I hit update on my app on the simulator (either the 1.0 release, or from https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/) it launches the simulator to the desktop but does not actually open the app. I have to browse to device and launch the app. My finger is getting tired :)

**Comment by mykmelez** [comment] 2013-01-28 19:03
We recently landed a change that should fix this problem. Can you reproduce it on the latest preview release?

Latest preview release: [Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), and [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi).

**Comment by mykmelez** [comment] 2013-03-29 17:30
Closing due to lack of needed info from reporter.

**Closed as completed by mykmelez** 2013-03-29 17:30 UTC
Labels: bug
