### ISSUE TITLE
Properties dictionary not being created correctly from the properties file

### ISSUE THREAD

**Issue by Vidhuran** [mozilla/r2d2b2g#364] opened 2013-03-08 15:05 UTC
The l10n.js file does not populate the properties dictionary gL10nData correctly. As a result of this, the value of the "#landing-clock" is not correct in the Home Screen.

Attached screenshot and error messages from the console log.

[17:00:56.317] [l10n] #shortTimeFormat is undefined.
[17:00:56.317] [l10n] #longDateFormat is undefined.
[17:00:56.318] [l10n] #weekday-5-long is undefined.
[17:00:56.319] [l10n] #month-2-long is undefined.
![Incorrect Date Format](https://f.cloud.github.com/assets/1607713/236893/93bf7d9e-8801-11e2-97b1-756bd24098e3.jpg)

**Comment by nickdesaulniers** [comment] 2013-03-09 00:09
This smells like a dupe of #330 and #333 .  I bet they are all related.

**Comment by nickdesaulniers** [comment] 2013-03-09 00:28
@mykmelez ,  I wonder if we need to be overriding the b2g locale?  The errors logged show that they are only defined for locale codes ['ar', 'en-US', 'fr', and 'zh-TW'].

@Vidhuran , please open a firefox console and execute "navigator.language" and paste the results here.  I bet it has to do with a Firefox locale that the isn't defined in the B2G locales, and there's no sane defaults yet.

**Comment by Vidhuran** [comment] 2013-03-09 04:49
@nickdesaulniers , I did try to do that earlier and got "en-US". 
If it is a problem only with Windows , could it be so that the .ini or .properties files are treated differently by Windows ?

**Comment by mykmelez** [comment] 2013-05-03 21:32
Closing this due to lack of needed info. But please do reopen if you can provide that info!

**Closed as completed by mykmelez** 2013-05-03 21:32 UTC
