### ISSUE TITLE
FF OS Simulator doesn't start. linux, debian sid, FF 18

### ISSUE THREAD

**Issue by ousado** [mozilla/r2d2b2g#261] opened 2013-01-23 02:17 UTC
debian sid, FF 18.0.1, starting the simulator gives following output/traceback in the console:

info: r2d2b2g: Simulator.onMessage getIsRunning
info: r2d2b2g: Simulator.onMessage listApps
info: r2d2b2g: Simulator.sendListApps
info: r2d2b2g: Simulator.onMessage listTabs
info: r2d2b2g: Simulator.onMessage getPreference
info: r2d2b2g: Simulator.onMessage toggle
error: r2d2b2g: An exception occurred.
Traceback (most recent call last):
  File "resource://r2d2b2g-at-mozilla-dot-org/addon-sdk/lib/sdk/timers.js", line 31, in notify
    callback.apply(null, args);
  File "resource://r2d2b2g-at-mozilla-dot-org/addon-sdk/lib/sdk/content/worker.js", line 109, in null
    self._emit.apply(self, JSON.parse(args));
  File "resource://r2d2b2g-at-mozilla-dot-org/addon-sdk/lib/sdk/deprecated/events.js", line 123, in _emit
    return this._emitOnObject.apply(this, args);
  File "resource://r2d2b2g-at-mozilla-dot-org/addon-sdk/lib/sdk/deprecated/events.js", line 153, in _emitOnObject
    listener.apply(targetObj, params);
  File "resource://r2d2b2g-at-mozilla-dot-org/addon-sdk/lib/sdk/content/worker.js", line 221, in postMessage
    self._addonWorker._emit('message', data);
  File "resource://r2d2b2g-at-mozilla-dot-org/addon-sdk/lib/sdk/deprecated/events.js", line 123, in _emit
    return this._emitOnObject.apply(this, args);
  File "resource://r2d2b2g-at-mozilla-dot-org/addon-sdk/lib/sdk/deprecated/events.js", line 153, in _emitOnObject
    listener.apply(targetObj, params);
  File "resource://r2d2b2g-at-mozilla-dot-org/r2d2b2g/lib/main.js", line 699, in onMessage
    simulator.run();
  File "resource://r2d2b2g-at-mozilla-dot-org/r2d2b2g/lib/main.js", line 588, in null
    defaultApp: appName
  File "resource://r2d2b2g-at-mozilla-dot-org/r2d2b2g/lib/remote-simulator-client.js", line 147, in null
    arguments: this.b2gArguments,
  File "resource://r2d2b2g-at-mozilla-dot-org/r2d2b2g/lib/remote-simulator-client.js", line 339, in null
    args.push("-dbgport", ""+this.remoteDebuggerPort);
  File "resource://r2d2b2g-at-mozilla-dot-org/r2d2b2g/lib/remote-simulator-client.js", line 395, in null
    serv.init(-1, true, -1);
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIServerSocket.init]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/XPIProvider.jsm -> file:///home/johnny/.mozilla/firefox/22ezz441.ffos/extensions/r2d2b2g@mozilla.org/bootstrap.js -> resource://r2d2b2g-at-mozilla-dot-org/addon-sdk/lib/toolkit/loader.js -> resource://r2d2b2g-at-mozilla-dot-org/r2d2b2g/lib/remote-simulator-client.js :: <TOP_LEVEL> :: line 395"  data: no]

**Comment by ousado** [comment] 2013-01-23 02:19
... and using version 2.0 pre4 FF OS Simulator - sorry.

**Comment by ousado** [comment] 2013-01-23 12:26
When using the nightlies for b2g I notice libxul.so requires glibc 2.14 - in debian sid the current version is still 2.13, so starting b2g fails with:
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by ./libxul.so)
Couldn't load XPCOM.
Might this be the issue why FF OS Simulator doesn't start up?

**Comment by mykmelez** [comment] 2013-01-28 19:17
The B2G Desktop nightlies are compiled against glibc 2.14, but the Linux builds we ship in Simulator are compiled against glibc 2.12, so that shouldn't be the problem. Unfortunately, I don't know what is, but @rpl might have an idea.

**Comment by rpl** [comment] 2013-01-28 19:52
That is the getter which detect a free port on the system when the
simulator is going to launch the b2g-desktop instance, and should not raise
that exception.

I'll try to reproduce the bug on a debian sid virtual machine asap, and
find a reason and a proper solution or workaround.

**Comment by psatler** [comment] 2013-01-29 22:06
It also affects me! I'm on Ubuntu 12.04 32bits. I've tried r2d2b2g versions 1.0 and 1.1 on today's Nightly.
I've disabled ubuntu mods and also created a new profile. Nothing helped.

Opening on terminal that's what I get:

info: r2d2b2g: Simulator.onMessage getIsRunning
info: r2d2b2g: Simulator.onMessage listApps
info: r2d2b2g: Simulator.sendListApps
info: r2d2b2g: Simulator.onMessage listTabs
info: r2d2b2g: Simulator.onMessage getPreference
info: r2d2b2g: Simulator.onMessage toggle
###!!! ABORT: X_GLXQueryServerString: BadRequest (invalid request code or no such operation): file /home/myk/Mozilla/central/toolkit/xre/nsX11ErrorHandler.cpp, line 157
###!!! ABORT: X_GLXQueryServerString: BadRequest (invalid request code or no such operation): file /home/myk/Mozilla/central/toolkit/xre/nsX11ErrorHandler.cpp, line 157
info: r2d2b2g: linux/b2g/b2g-bin terminated with 0

**Comment by mykmelez** [comment] 2013-01-29 22:27
@psatler: you're actually experiencing a different problem: issue #123.

**Comment by mykmelez** [comment] 2013-05-13 16:54
@rpl Were you able to reproduce this?

**Comment by rpl** [comment] 2013-05-14 09:39
Unfortunately debian sid is not a release but a moving target (it's the codename of the debian unstable repo),
I've tried on Debian 7.0 "Wheezy" 64bit (which should be the last release spawned by sid) and I'm not able
to reproduce the problem on Firefox 18.0 / 18.0.1 / 20

Follows logs collected to better define the test accomplished:

**RESULT:** Unable to reproduce

**LSB_RELEASE:**
  Distributor ID:   Debian
  Description:  Debian GNU/Linux 7.0.0 (wheezy)
  Release:  7.0.0
  Codename: wheezy

**R2D2B2G COMMIT SHA1:**
  cd65ca1cfe57c257795b9c58879df723b5703d88

**B2G OPENGL INIT CONSOLE LOG:**
  OpenGL LayerManager Initialized Succesfully.
  Version: 2.1 Mesa 8.0.5
  Vendor: VMware, Inc.
  Renderer: Gallium 0.4 on llvmpipe (LLVM 0x209)
  FBO Texture Target: TEXTURE_2D

**TEST OPENGL BASED GAIA APP (crystalskull error log):**
  Timestamp: 05/14/13 11:19:11
  Warning: Error: WebGL: Can't get a usable WebGL context
  Source File: app://5f6c0f99-b32b-4178-92a1-59cb8263e0c5/j3d.js
  Line: 52

**Comment by mykmelez** [comment] 2013-05-17 17:09
@rpl Thanks for testing!

@ousado Are you still experiencing this problem, and if so, what versions of Debian and Firefox are you now using? It would also be helpful to know if you're using a Mozilla build of Firefox or a Debian build of IceWeasel and whether you're using a 32-bit or 64-bit installion of the OS.

**Comment by mykmelez** [comment] 2013-07-19 00:39
Closing due to lack of info needed. But please reopen if you can provide it!

**Closed as completed by mykmelez** 2013-07-19 00:39 UTC
Labels: bug
