### ISSUE TITLE
Browser crashes when I open simulator 3.0pre3 on ubuntu 13.04

### ISSUE THREAD

**Issue by suoko** [mozilla/r2d2b2g#394] opened 2013-03-26 09:20 UTC
The simulator starts and works but the browser crashes (both stable and aurora browser).
I can reopen the browser but in new browser session the simulator looks stopped therefore I can't test any app.

**Comment by mykmelez** [comment] 2013-03-29 21:31
I have an Ubuntu 12.10 64-bit installation, and I can't reproduce this problem there on Firefox 19.0.2. But perhaps it's specific to Ubuntu 13.04? You might try the [latest preview build for Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi) to see if it fixes the problem.

**Comment by mykmelez** [comment] 2013-05-03 22:54
I just heard from @dholbert that Simulator 3.0 final works on his Ubuntu 13.04 installation (albeit with some painting problems), so I'm going to close this issue. But please reopen if you can still reproduce with the latest preview build ([Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), and [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi)).

**Closed as completed by mykmelez** 2013-05-03 22:54 UTC
