### ISSUE TITLE
Unable to make XMLHttpRequests with cached page

### ISSUE THREAD

**Issue by rheschner** [mozilla/r2d2b2g#335] opened 2013-02-28 03:05 UTC
I have a simple web application with one page that get some information from the server and then redirect to another page (to an iframe). To get this information I use ajax request (jquery). This page must be cached, with "manifest='cache.appcache' " in the HTML tag. 
This works fine in Windows, Lunux and Android, but in the simulator it gives an error in this ajax request to server. I could't find any description of the error, the console also doesn't show anything.
I found out that clearing the cache and remove the "manifest='cache.appcache' ", the request works fine, but then the page can't be access off-line and this is a problem.
I'm sending the information about the app:

Manifest: http://www.homemanager.com.br/manifest.webapp
WebApp Page: www.homemanager.com.br/webapp.html

Thanks in advance

**Comment by nickdesaulniers** [comment] 2013-03-07 22:44
When I try to login with this app installed I see "Não foi possível acessar a central de controle. Verifique sua conexão com a internet. Feche o aplicativo e tente novamente", which according to google translate means "Unable to access the control center. Check your internet connection. Close the application and try again."

I'd recommend listening for the [online event](https://developer.mozilla.org/en-US/docs/Online_and_offline_events) instead of prompting your user to close out of the app entirely.

So the problem is that there appears to be a failure when making a XHR to a URL listed in an AppCache manifest?  There are no errors logged?  Am I understanding the problem cirrectly?  Thanks for the assistance!

**Comment by nickdesaulniers** [comment] 2013-03-07 22:48
Also, this sounds like a dupe of #306

**Comment by rheschner** [comment] 2013-03-08 01:11
Hi, thanks for the reply.

The issue #306 is about the installation, this one is another problem, nothing to do with the installation (the problem also happens when you access the informed "WebApp Page" directly).
The problem is when making a XHR yes, but the URL of this request is not cached, only the "WebApp Page" is cached.

I've created another page, its exaclty the same as the webapp.html, but I removed the cache manifest in the html tag. Here is the URL.
WebApp Page 2: www.homemanager.com.br/webapp2.html

You can put the user as "eschner" to test. The correct behavior is to show another login screen, this happens when you use the webapp2.html (no cached). But if you use the webapp.html (cached), it appears the error you describe, and that should not happen. 

The URL that the webapp.html fail to access is "http://www.homemanager.com.br/HomeRedirect/getURLs.do", it's a Java application in the same domain. This page must not be cached in any way.

No error is logged in the simulator console.

**Comment by rheschner** [comment] 2013-03-21 00:52
Hi, I found that this is not related to the emulator, it was a cache problem.
The page that makes the XHR is a cached page, but the URL that is requested is not (must not). I have to specify that this URL must not be cached explicitly (using "NETWORK: [URL]" in the cache manifest file).

**Closed as completed** 2013-03-21 00:52 UTC
Labels: info-needed
