### ISSUE TITLE
Won't run, Firefox 20, MacOS 10.6.8

### ISSUE THREAD

**Issue by winncountynews** [mozilla/r2d2b2g#501] opened 2013-05-05 10:41 UTC
I can install the plugin/app in Firefox 20.0 under MacOS 10.6.8 but can't run the simulator. When I enabled it, it crashes. All other non-standard Firefox plugins disabled. Also, you really need to post some sort of guide, there's no documentation at all that I can find.

**Comment by mykmelez** [comment] 2013-05-13 18:17
Hi @winncountynews, I'm sorry to hear that the Simulator is crashing for you! There are [docs on the Mozilla Developer Network](https://developer.mozilla.org/en-US/docs/Tools/Firefox_OS_Simulator), although I doubt they are helpful in this situation.

I don't have a Mac OS 10.6 installation, but I've tested on 10.7 and 10.8 with the [latest preview build for Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), and I haven't been able to reproduce this problem. What version of the Simulator are you using, and can you try that latest preview build to see if it fixes this problem?

**Comment by mykmelez** [comment] 2013-05-20 17:12
Closing due to lack of needed info, but please reopen if you can provide more details!

**Closed as completed by mykmelez** 2013-05-20 17:12 UTC

**Comment by winncountynews** [comment] 2013-05-20 18:18
the problem is still there, what info did you need.

for example start at
http://www.ada.org/8544.aspx

answer the questions to test question 1, click SUBMIT at bottom of page
you should be taken to
https://jadace.ucdenver.edu/index.php?TestID=2013_05&Q1=A&Q2=A&Q3=A&Q4=A&Q5=null&Q6=null&Q7=null&Q8=null&Q9=null&Q10=null&Q11=null&Q12=null&Q13=null&Q14=null&Q15=null&Q16=null&MemNum=

(slightly different URL from original request)

Sincerely,
Paul Gorski

Search safely and don't be tracked at DuckDuckGo.com.

-----Original Message-----

**Comment by mykmelez** [comment] 2013-06-10 23:07
@winncountynews I don't understand how that survey is related to the problem you reported, which was an inability to run the Simulator. Can you elaborate?
