### ISSUE TITLE
cross-domain XMLHttpRequests are not working

### ISSUE THREAD

**Issue by zalun** [mozilla/r2d2b2g#251] opened 2013-01-09 16:55 UTC
I'm adding the app in the Dashboard

app: https://github.com/zalun/rssFeeds.lib/tree/master/test

permission: https://github.com/zalun/rssFeeds.lib/blob/master/test/manifest.webapp#L21
xhr code: https://github.com/zalun/rssFeeds.lib/blob/master/test/js/app.js#L25

I'm trying to open example.com. 

I should see "SUCCEED!"

I see "FAILED. Status code: 0"

**Comment by digitarald** [comment] 2013-01-09 17:00
Permissions are currently not added in the Simulator for either packaged or hosted apps, due to the way we install them. They are added to your browser though, so adding a hosted app with permissions will unlock those permissions for the given origin.

**Comment by mykmelez** [comment] 2013-01-28 19:04
We recently landed a change that should register permissions, so this should now work. Can you still reproduce it with the latest preview release?

Latest preview release: [Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), and [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi).

**Comment by mykmelez** [comment] 2013-03-29 17:30
Closing due to lack of needed info from reporter. Please reopen if you can still reproduce!

**Closed as completed by mykmelez** 2013-03-29 17:30 UTC
Labels: info-needed
