### ISSUE TITLE
FirefoxOS simulator incorrect screen width/height values

### ISSUE THREAD

**Issue by eludi** [mozilla/r2d2b2g#249] opened 2013-01-04 15:18 UTC
The FirefoxOS simulator 1.0, run on MS Windows Firefox 17.0.1, provides as Javascript variable values screen.width, screen.height, screen.availWidth, screen.availHeight the values of the host screen, not of the simulated device. The same holds true for CSS mediaqueries.
This makes the simulator impractical for testing websites/apps that use these parameters for switching their layout between desktop or mobile. 

example site: http://eludi.net

**Comment by mykmelez** [comment] 2013-01-28 19:01
This is a duplicate of issue #7.

**Closed as completed by mykmelez** 2013-01-28 19:01 UTC
