### ISSUE TITLE
Installed the firefox os simulator on firefox linux - then on firefox windows. doesn't work on win

### ISSUE THREAD

**Issue by Pikkolo** [mozilla/r2d2b2g#334] opened 2013-02-27 19:08 UTC
Hello there :)

I have installed firefox os simulator on my linux distro on my pc. it worked perfect. then i have booted to win on my pc, setup firefox os simulator on firefox . it doesn't work. i click on the simulator stopped / running switch, but nothing happens.

Any hints ?

Thanks <3

**Comment by nickdesaulniers** [comment] 2013-03-07 22:46
@Pikkolo , thanks for the feedback, every little bit helps!  Can you please try updating to the latest version that was released 2 days ago (3.0pre2) and helping us verify this issue?  We'd appreciate the help!

**Comment by Pikkolo** [comment] 2013-03-08 06:53
Hi :) I'll be afk until saturday night but for now i have updated the versions on both win and linux. result ? nothing works :(

**Comment by Pikkolo** [comment] 2013-03-11 12:05
Hello there, any news ? The simulator continues not to work both on linux and win7 :'(

**Comment by nickdesaulniers** [comment] 2013-03-11 16:18
New build scheduled for Wednesday, possibly.

**Comment by mykmelez** [comment] 2013-03-29 18:31
The latest build is from two days ago, so you might try that.

Latest preview build: [Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), and [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi).

Two questions:
1. Accented characters in file paths are a known problem (issue #247). What is the path to your $HOME directory on those two systems?
2. If you start Firefox from a terminal window on Linux (or on Windows with the -console flag), do you see any messages related to the Simulator in console output?

**Comment by Pikkolo** [comment] 2013-04-08 19:34
I m very busy and I cannot make a detailed feedback. I can just say that the last release is now working on my linux os and it is not working on windows.

**Comment by mykmelez** [comment] 2013-04-08 22:12
@Pikkolo thanks for letting us know that it works for you on Linux! I would be happy to help diagnose the problem on Windows, but I would need more information in order to do so. And I understand that you're too busy to provide it at the moment. So I'm going to go ahead and close this issue. But please do reopen it if you have time to provide more information in the future! (In particular, I would need to know about any messages that appear in the Error Console when you start the Simulator after using about:config to add the preference extensions.r2d2b2g@mozilla.org.sdk.console.logLevel and set it to the integer value 0.)

**Comment by Pikkolo** [comment] 2013-04-08 22:53
Hi, I have added the string ext... to the about:config page and set it to integer value 0.
What happens ( and already happened before this string added ) is that whether i flag or don't flag the console option, when I launch the os simulator from the simulator dashboard, apparently nothing happens. Neither the console nor the simulator window appear :o Hope i can help, let me know how :) Cheers

**Comment by mykmelez** [comment] 2013-04-09 00:03
Sorry, I wasn't clear, I meant to look at the Error Console in Firefox, i.e. Tools > Web Developer > Error Console. Try opening that console, then starting the Simulator, and see if any messages appear.

**Comment by Pikkolo** [comment] 2013-04-09 15:31
I opened first the error console than the simulator and tons of warnings were listed. But aftert closing firefox, restarting it and trying again, no messages have been shown :o

**Comment by mykmelez** [comment] 2013-04-11 17:51
If you press the Errors button in the console, then it should show you only errors, which makes it easier to see if there are any actual errors instead of just a bunch of warnings. You can also do this for messages with the Messages button, and that would be particularly useful, since the Simulator writes a number of messages to the console, and it would be useful to know if it's doing that in your case.

**Comment by Pikkolo** [comment] 2013-04-11 18:18
Ok, i have just done what you suggested. No messages, no errors displayed :o

**Comment by mykmelez** [comment] 2013-04-11 19:25
Hmm, that's strange. Even if the addon fails to start the Simulator, it should still write some messages to Firefox's Error Console once you've set that preference.

What is the filesystem path to your home directory? Does it happen to contain any accented characters (f.e. in your username)?

**Comment by Pikkolo** [comment] 2013-04-11 21:07
my username is Pikkolo ... there is no accented characters at all :o i ll wait for next requests <3

**Comment by Pikkolo** [comment] 2013-04-12 23:06
Now I have found some messages :o: 

Data e ora: 13/04/2013 01:02:52
Errore: [Exception... "'ReferenceError: self is not defined' when calling method: [nsITimerCallback::notify]"  nsresult: "0x8057001c (NS_ERROR_XPC_JS_THREW_JS_OBJECT)"  location: "native frame :: <unknown filename> :: <TOP_LEVEL> :: line 0"  data: no]

i have just been able to copy one in this message, then i went back to the console and the other 2s are gone :(

**Comment by mykmelez** [comment] 2013-04-12 23:30
I've been diagnosing several issues with Windows builds, and I found a couple problems, so I created a test build with fixes for them.

https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-3.0pre6dev-windows.xpi

I'm not sure this build will resolve your issue, but please try it out, and let me know how it works for you!

**Comment by Pikkolo** [comment] 2013-04-13 02:31
Just installed it and tried to start it without restarting firefox

Data e ora: 13/04/2013 04:28:55
Errore: can't access dead object
File sorgente: resource://gre/modules/XPIProvider.jsm -> file:///C:/Users/Pikkolo/AppData/Roaming/Mozilla/Firefox/Profiles/7pinr898.default/extensions/r2d2b2g@mozilla.org/bootstrap.js -> resource://r2d2b2g-at-mozilla-dot-org/addon-sdk/lib/toolkit/loader.js -> resource://r2d2b2g-at-mozilla-dot-org/addon-sdk/lib/sdk/addon-page.js
Riga: 39

Now i ll also try to restart firefox

**Comment by Pikkolo** [comment] 2013-04-13 02:33
Restarted firefox and started again firefox os sim, nothing happens and nothing shown on the error console.

I m ready for new requests whenever

Cheers

**Comment by mykmelez** [comment] 2013-04-18 02:26
I just pushed new preview builds ([Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi)). They should resolve that "can't access dead object" error. But I'm not sure that's related to your problem starting the Simulator. In any case, it's worth trying these new builds to see if they help. Sorry I don't have more specific guidance at this point!

**Comment by Pikkolo** [comment] 2013-04-18 02:49
Hooray <3 it works :D gratz <3 all the best to you, all the best to mozilla :D

**Comment by mykmelez** [comment] 2013-04-18 04:44
Woohoo, that's great! Thanks for sticking with us through all the testing, @Pikkolo!

**Comment by Pikkolo** [comment] 2013-04-18 10:38
Ok bad news again :D But maybe I understood why and how to make the firefox os simulator NOT to work on windows. I have started the sim by clicking on the firefox dock button. but then i have closed the firefox simulator window without clicking on the dock button. i have then restarted firefox, and the simulator doesn't start anymore. err .. success ? :D

**Comment by mykmelez** [comment] 2013-04-18 20:24
By "dock button", do you mean the button in the Dashboard interface that opens in a tab when you select Web Developer > Firefox OS Simulator? If so, then it should be ok to close the Simulator window without clicking on that button. It isn't necessary to click on that button to close the Simulator.

However, if the Simulator process failed to stop for some reason, then that might explain why you can't start it anymore. If you go to the Windows Task Manager (Ctrl-Shift-Escape), does it list a "b2g.exe" process in its Processes tab? If so, trying selecting it, clicking the End Process button, and confirming that you want to end the process. Then go back to the Dashboard and see if you can run the Simulator.

**Comment by mykmelez** [comment] 2013-04-18 20:26
cc: @ochameau for his thoughts on this one too!

**Comment by Pikkolo** [comment] 2013-04-18 20:34
As I wrote before, I am still now unable to start the simulator again. nothing happens ... just like what i described in the first post on this issue :(

**Comment by mykmelez** [comment] 2013-04-18 21:19
@Pikkolo Did you try going to the Task Manager to see if there's a hung b2g.exe process?

**Comment by Pikkolo** [comment] 2013-04-18 21:20
Yeah. It neither appears or disappears. No sights of b2g.exe process :(

**Comment by ochameau** [comment] 2013-04-22 12:57
I think that the dock icon Pikkolo is refering to are the Windows seven new task bar that is similar to the Mac dock now.
@Pikkolo Do you still see error in the JS console? If yes, may you paste them again? 
I tried hard to test various random way to launch'n close firefox with the simulator and wasn't able to reproduce your issue.

**Comment by Pikkolo** [comment] 2013-04-22 13:16
When i refer to the dock, it's the Simulator Dashboard " start / stop " dock button :o

**Comment by mykmelez** [comment] 2013-04-26 00:21
I'm stumped.

I tried various ways to reproduce this issue, but I haven't been successful. And without being able to reproduce it, it's very hard to resolve it. Nevertheless, it's still important to resolve, because if one person is having it, then probably many others are too. But I don't know what to do next, and it's also important to release the next version for folks who can use it.

So I'm going to move this out of the v3 milestone, but I'll continue to think about ways to reproduce it or improve logging in the addon so you can provide us with logs that explain what is happening on your system.

**Comment by nickdesaulniers** [comment] 2013-04-26 16:00
Maybe Pikkolo could make a video of the issue for us, since 1000 rapidly moving images are worth 1,000,000 still images, which are worth 1,000,000,000 words!

**Comment by Pikkolo** [comment] 2013-04-29 15:34
Data e ora: 29/04/2013 17:29:59
Errore: TypeError: aDoc.location is null
File sorgente: chrome://fgm/content/fgm.js
Riga: 379

Data e ora: 29/04/2013 17:32:36
Errore: [Exception... "'ReferenceError: self is not defined' when calling method: [nsITimerCallback::notify]"  nsresult: "0x8057001c (NS_ERROR_XPC_JS_THREW_JS_OBJECT)"  location: "native frame :: <unknown filename> :: <TOP_LEVEL> :: line 0"  data: no]

Data e ora: 29/04/2013 17:32:53
Errore: can't access dead object
File sorgente: resource://gre/modules/XPIProvider.jsm -> file:///C:/Users/Pikkolo/AppData/Roaming/Mozilla/Firefox/Profiles/7pinr898.default/extensions/r2d2b2g@mozilla.org/bootstrap.js -> resource://r2d2b2g-at-mozilla-dot-org/addon-sdk/lib/toolkit/loader.js -> resource://r2d2b2g-at-mozilla-dot-org/r2d2b2g/lib/simulator.js
Riga: 1084

Data e ora: 29/04/2013 17:32:53
Errore: L'esposizione di oggetti chrome JS nel contenuto senza **exposedProps** non è sicura ed è deprecata. Per ulteriori informazioni consultare https://developer.mozilla.org/en/XPConnect_wrappers.
File sorgente: resource://gre/modules/XPIProvider.jsm -> file:///C:/Users/Pikkolo/AppData/Roaming/Mozilla/Firefox/Profiles/7pinr898.default/extensions/r2d2b2g@mozilla.org/bootstrap.js -> resource://r2d2b2g-at-mozilla-dot-org/addon-sdk/lib/toolkit/loader.js -> resource://r2d2b2g-at-mozilla-dot-org/r2d2b2g/lib/adb.js
Riga: 414

**Comment by Pikkolo** [comment] 2013-04-29 15:44
The simulator works fine now, no more strange behaviours detected :love:

Let's see if it lasts long :D

**Comment by mykmelez** [comment] 2013-04-29 23:48
@Pikkolo Note that I fixed another "can't access dead object" error today in https://github.com/mozilla/r2d2b2g/commit/76c2db21ea8e52483a0b5809c7d6a5410e0ec500, and the fix made it into the 3.0 release candidate builds:

Windows: https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-3.0-windows.xpi
Mac: https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-3.0-mac.xpi
Linux: https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-3.0-linux.xpi

But you need to restart Firefox after installing the build to make the fix take effect. So if you experience the problem again, then you might try installing one of those builds. Or just wait until we release 3.0 on Thursday and Firefox checks for updates, whereupon it will prompt you to install the update automatically!

**Comment by mykmelez** [comment] 2013-05-03 22:35
I'm going to close this, as @Pikkolo reports that the Simulator works for him, and I think I fixed the last "can't access dead object" bug. Whew!

**Comment by nickdesaulniers** [comment] 2013-05-03 22:36
Nice work @mykmelez , we can probably close #493 then?

**Closed as completed by mykmelez** 2013-05-03 22:35 UTC

**Comment by mykmelez** [comment] 2013-05-03 22:38
@nickdesaulniers Yes, I think so! But please reopen if you still experience the problem!
