### ISSUE TITLE
Gallery app overlaps home button

### ISSUE THREAD

**Issue by waldyrious** [mozilla/r2d2b2g#198] opened 2012-12-12 01:48 UTC
Opening a picture on the gallery app (not just launching the app) makes the bottom bar with the home button disappear.

**Comment by mykmelez** [comment] 2012-12-27 21:50
The toolbar with the Home button reappears if you exit the app (f.e. by using the Home key on your keyboard), so it's possible to work around this problem. Nevertheless, it shouldn't happen! Especially since the keyboard shortcut is not obvious, so it's possible to get into a state you don't know how to get out of.

**Comment by mykmelez** [comment] 2013-03-29 18:13
I can't reproduce this anymore. First I press the Home and End keys simultaneously to create a screenshot, then I start the Gallery app and click the screenshot to view it. After which I still see the bottom bar.

I wonder if we fixed this when we undid a bunch of style that B2G adds by default. In any case, I'm closing this issue, as it appears that we resolved it. But please reopen if you can still reproduce on the latest preview build!

Latest preview build: [Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), and [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi).

**Closed as completed by mykmelez** 2013-03-29 18:13 UTC
Labels: bug, P2

**Comment by waldyrious** [comment] 2013-04-01 15:41
Confirmed, I can't reproduce it anymore either.
