### ISSUE TITLE
under windows 7 I have an ugly representation of the time

### ISSUE THREAD

**Issue by stefanostatuti** [mozilla/r2d2b2g#545] opened 2013-05-22 12:42 UTC
under windows 7 Ultimate 32Bit whit FFOS simulator v3.0 when start the emulator i have an ugly rappresentation of the time. I haven't this problem under  Ubuntu 12.4 whit the same browser (v 22 beta italian)

![timebug](https://f.cloud.github.com/assets/4499372/548175/00104800-c2dd-11e2-88e1-7df6cf54a5fc.jpg)

**Comment by nickdesaulniers** [comment] 2013-05-22 23:57
Duplicate of #502 

@stefanostatuti , please try updating your version of the Firefox OS Simulator:

Latest preview build: [Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), and [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi).

**Closed as completed by nickdesaulniers** 2013-05-22 23:57 UTC

**Comment by nickdesaulniers** [comment] 2013-05-23 00:02
@stefanostatuti , ah so in #502, it looks like the patch just landed in gaia which will be updated in the next preview build of the simulator, which will be tomorrow or the day after.  Please use the above links to install the latest build later this week, and reopen if it's not solved.  If you need to reopen, please also post your simulator version, which can be found by going to about:addons.  Thanks!

**Comment by stefanostatuti** [comment] 2013-05-25 15:41
ok, fixed. You can close this issue
