### ISSUE TITLE
homescreen transition from mouse "swipe" sometimes gets stuck

### ISSUE THREAD

**Issue by Jaxo** [mozilla/r2d2b2g#206] opened 2012-12-12 15:48 UTC
Running Ubuntu 12.04.1 / 32 bits - Firefox 17.0.1 - gnome.
The simulator has troubles at refreshing.  For example, the display stops right in the middle of a page transition, after a swipe.  
- It doesn't _always_ do that,. 
- Stopping/restarting the simulator may remedy to the problem. 
- It doesn't prevent me to do my tests, and, except for this, R2D2B2G works very well.

A simple workaround consists to activate another window, and go back to the simulator window.  Just annoying, nothing more!

**Comment by mykmelez** [comment] 2012-12-12 18:45
When it freezes in the middle of a page transition, does clicking and dragging again do anything? Or does it stop responding to input entirely until you activate another window and then go back to it?

**Comment by Jaxo** [comment] 2012-12-13 07:08
The latter: it stops responding entirely until another window is activated AND the simulator is again activated.  Then, the transition finishes.
[Sorry for the delay: CET TimeZone]

**Comment by Jaxo** [comment] 2012-12-13 07:13
**To be exact**, when you go back to the simulator the transition _is_ finished.  It is very well possible that the controls in the simulator are still alive, despite the fact that the simulator display is frozen.  E.g: to unfreeze the display requires to click another windows, and click the window simulator back.

**Comment by Jaxo** [comment] 2012-12-26 07:15
Soon after this post I noticed that, by successively stopping/reopening the simulator a few times, it eventually ended working normally.  
This is: if the "mozilla" white on black logo is displayed, but nothing else, stop and start again.

**Comment by mykmelez** [comment] 2012-12-27 22:06
@digitarald plans to make mouse button presses generate touch events over in #166, and I wonder if that will fix this issue.

> Soon after this post I noticed that, by successively stopping/reopening the simulator a few times, it eventually ended working normally.

This is a different issue that is likely to be caused by a stuck B2G process. The workaround for this is to kill any b2g or b2g-bin processes running on your system. Restarting your computer will also do the trick.

**Comment by Jaxo** [comment] 2013-03-25 16:33
There are still few refresh problems:
- console doesn't clear, except if you then move the console window a bit
- less problems on the simulator window, 
- if you play with the gallery, it shows a dark screen 
  The simulator does not die, however.  Reopening it definitively fixes it.  Haven't seen much orphans processes..

Anyway: 3.0 is so wonderful that I feel a bit blushing reporting the above :-)

**Comment by Jaxo** [comment] 2013-03-25 16:34
Ooops... wrong button.

**Comment by mykmelez** [comment] 2013-03-29 18:38
@Jaxo no worries, we want to hear about all problems, no matter how minor! I'm not sure you're experiencing the same problem, though. The console window issue sounds like a painting problem. And the gallery issue might be the same painting problem, but it could also be something else. But neither sound like the original problem of the homescreen transition getting stuck.

I haven't noticed these new issues myself on a similar test system (Ubuntu 11.10 32-bit, Firefox 19.0.2, gnome) with the latest preview build, which I just published two days ago. Can you try reproducing with it? 

Latest preview build: [Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), and [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi).

**Comment by mykmelez** [comment] 2013-05-03 22:17
Closing due to lack of info, but please do reopen if you still see the problem(s) with the latest preview builds!

**Closed as completed by mykmelez** 2013-05-03 22:17 UTC
Labels: bug
