### ISSUE TITLE
scrollbar appears in various apps

### ISSUE THREAD

**Issue by Maksims** [mozilla/r2d2b2g#379] opened 2013-03-16 20:07 UTC
Scroll bar is visible on Windows emulator.
Just run it, and get top panel out.
And all applications that dont fit vertically. Even worse when app need whole width, and it will show horizontal scroll bar as well.

Maybe it is time for Mozilla to think about transparent scroll bar like on Mac OS X in Chrome?

**Comment by mykmelez** [comment] 2013-03-29 19:52
I see this on all platforms and multiple apps, including Gallery (when pictures are present) and Settings. I think it's a regression from removal of the B2G stylesheet.

@nickdesaulniers I think we're going to have to reintroduce that stylesheet, limiting it to the chrome of apps running in the shell, so it applies to those apps but doesn't apply to the chrome of the Simulator XUL application itself. I don't actually know how to do that, however.

**Comment by rpl** [comment] 2013-03-29 20:23
@mykmelez @nickdesaulniers I've already prototyped reinjection of b2g
mobile stylesheets, I'm waiting to push because it depends on mutation
observers introduced in the pull request #377

**Comment by mykmelez** [comment] 2013-04-04 00:07
Fixed by #402.

**Closed as completed by mykmelez** 2013-04-04 00:07 UTC
Labels: bug, P1
