### ISSUE TITLE
Iceweasel 22.0a.2

### ISSUE THREAD

**Issue by TDYK** [mozilla/r2d2b2g#423] opened 2013-04-11 13:29 UTC
Hello!
I have Iceweasel, installed on Debian Sid/Experimental from http://mozilla.debian.net/ repo.
Just installed FireFoxOS Simeulator v.3.0pre5, and can not run it. There is the output from terminal:
http://paste.debian.net/248890/
The old version (v.2) worked fine for me.

Best regards, 
Dmitri.

**Comment by mykmelez** [comment] 2013-04-11 17:29
3.0pre5 uses Add-on SDK 1.14, which perhaps isn't compatible with Iceweasel anymore?

cc: @ochameau and @gozala for their thoughts.

**Comment by ochameau** [comment] 2013-04-15 12:26
Oh, it looks like a bug introduced with the new compatibility per module feature.
I opened a bug about that: https://bugzilla.mozilla.org/show_bug.cgi?id=861826

**Comment by nickdesaulniers** [comment] 2013-04-25 22:42
The above referenced bug was marked as a [dupe of a bug](https://bugzilla.mozilla.org/show_bug.cgi?id=855651) that was marked resolved on 4/20/13.  Not sure if it has made it yet into release versions of Ice Weasel, or if we need to update our version of the Add-on SDK? @mykmelez

**Comment by mykmelez** [comment] 2013-04-25 23:04
Firefox now ships with cuddlefish.js, but the Simulator also ships with its own copy of cuddlefish.js from Add-on SDK 1.14, and I'm not sure which version it prefers when both are available.

If it prefers Firefox's version, then Iceweasel will work once it pulls upstream changes from Firefox after Firefox pulls upstream changes from Add-on SDK. Otherwise, Iceweasel won't work until the Simulator updates the version of the Add-on SDK it uses.

cc: @ochameau, @gozala, @zer0, @canuckistani, and @mossop, one of whom certainly knows!

**Comment by TDYK** [comment] 2013-04-25 23:11
Hi. 
IDK, if it is that thing, when i tried to make some changes in cuddlefish.js form ~/.mozilla/firefox/xwskga81.default/extensions/r2d2b2g@mozilla.org/resources/addon-sdk/lib/sdk/loader/
nothing happened, because it was 
jar:file:///usr/lib/iceweasel/xulrunner/omni.ja!/modules/commonjs/sdk/loader/cuddlefish.js
in use.

**Comment by ochameau** [comment] 2013-04-25 23:13
Repacking won't have any effect on cuddlefish on Firefox/Iceweasel 21+.
Starting with 21 and when using SDK 1.14+, we always use firefox modules, even cuddlefish.
The only one file that can require a repack is bootstrap.js and eventual modification being done to the harness-option manifest.

**Comment by mykmelez** [comment] 2013-05-03 23:08
Ok, then it sounds like the issue is with the loader in Iceweasel, which needs to pull the fix that landed a few days ago in Aurora and Beta ([bug 855651](https://bugzilla.mozilla.org/show_bug.cgi?id=855651)). So there's nothing for us to do on the Simulator side of things. Thus I'm going to close this issue.

**Closed as completed by mykmelez** 2013-05-03 23:08 UTC

**Comment by white-gecko** [comment] 2013-05-18 21:05
Sorry for the question, but for which iceweasel version do I have to wait to try FirefoxOS again?
21.0?

**Comment by TDYK** [comment] 2013-05-19 18:06
Well, i tried 22 ant it is working. But, in v.23 it fails to start again.

You should try v.22, before the bug is fixed in v.23.

So, can someone tell me please, where must i create a bug report, according
to attached file?
Must I open one here, or send it to iceweasel maintaners?
http://paste.debian.net/5217/

Thank you!
Best regards,
Dmitrii
