### ISSUE TITLE
Messages Contact Search feature not showing any results

### ISSUE THREAD

**Issue by ghost** [mozilla/r2d2b2g#286] opened 2013-02-01 05:52 UTC
When searching for contacts in the native Messaging App, nothing happens and no results show. With plenty of contacts manually added too. Simply hitting Enter on the physical keyboard seems non functional and it's the same with the built-in keyboard.

**Comment by mykmelez** [comment] 2013-03-29 17:55
Sorry for the delay responding! This was presumably a problem with Firefox OS, not the Simulator. But since the Messaging app exposes web activities to other apps, this might affect app developers. So it's worth investigating as a Simulator issue. Nevertheless, I can't reproduce this on the latest preview build. Perhaps we fixed it in the last couple months. Therefore I'm closing the issue, but please reopen if you can still reproduce on the latest preview build!

Latest preview build: [Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), and [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi).

**Closed as completed by mykmelez** 2013-03-29 17:55 UTC
