### ISSUE TITLE
mousedown-scroll becomes drag-drop, continues scrolling after mouseup

### ISSUE THREAD

**Issue by hkgrild** [mozilla/r2d2b2g#114] opened 2012-11-16 18:24 UTC
Pressing down the mouse button and dragging with the mouse (to simulate a tap-and-swipe on a device) while in the Settings app causes the interface to scroll for only a short distance before a translucent icon appears next to the cursor as if a drag-and-drop action has been initiated.

Then, if you release the mouse button and continue to drag the mouse, the interface starts to scroll again. And it doesn't stop scrolling until you click somewhere (which then activates the item you clicked).

Whereas what should happen instead is that the interface scrolls without showing an icon as long as the mouse button is pressed, and it stops scrolling once the mouse button is released.

**Comment by mykmelez** [comment] 2012-11-16 23:58
If I understand this report correctly, the issue is that pressing down the mouse button and dragging with the mouse (to simulate a tap-and-swipe on a device) while in the Settings app causes the interface to scroll for only a short distance before a translucent icon appears next to the cursor as if a drag-and-drop action has been initiated.

Then, if you release the mouse button and continue to drag the mouse, the interface starts to scroll again. And it doesn't stop scrolling until you click somewhere (which then activates the item you clicked).

Whereas what should happen instead is that the interface scrolls without showing an icon as long as the mouse button is pressed, and it stops scrolling once the mouse button is released.

I see this too, and while it is probably an issue with B2G Desktop itself (it doesn't happen in my tests on a B2G phone), and it isn't yet known to affect app developers testing their own apps, it seems likely to affect those developers, so it's worth tracking here as a Simulator issue.

**Comment by mykmelez** [comment] 2012-11-16 23:59
> Also, clicking on any 'Radio button' like an asshole , doesn't change the parameter... i need to click gently on it :x

Please limit each report to a single issue! Otherwise it becomes difficult to track their resolution.

**Comment by mykmelez** [comment] 2012-12-27 20:57
I think this is because the mouse button presses are triggering mouse events instead of touch events, and the Settings app is designed to respond to touch events. @digitarald plans to address this problem in the next release by making mouse button presses generate touch events instead of mouse events. Leaving this bug open until that fix lands and we can confirm that it fixes this problem.

**Comment by mykmelez** [comment] 2012-12-27 21:23
The issue tracking @digitarald's changes is #166.

**Comment by mykmelez** [comment] 2013-05-03 22:02
We didn't end up landing this for the release, but it'll be a top priority for the next one. Let's track it in #166, though, as it seems like this issue is just another manifestation of the problem that other issue is resolving.

**Closed as completed by mykmelez** 2013-05-03 22:02 UTC
