### ISSUE TITLE
Some small bugs-Firefox OS

### ISSUE THREAD

**Issue by Pipelinetester1** [mozilla/r2d2b2g#369] opened 2013-03-10 23:34 UTC
First of all,I have to say that you have done an amazing work here. Firefox OS is amazing!
I've detected a few "bugs"  : 
1. Some buttons are overlaying
2. The games installed by default are not fitting in the screen and but you can drag them
3. The virtual keyboard is missing sometimes.
4. The buttons from the notification tab are not working.
 Etc.
I've made a video where you can notice all the bugs:
http://www.youtube.com/watch?v=aHlQZjvLEXc

I am sorry if I've re-posted those bugs or they are already known,I had no time to watch all the issues from the list. Hope that the video helps.

Yours faithfully,
Osman A.

**Comment by nickdesaulniers** [comment] 2013-03-11 17:43
@wizgothic , Hey thanks for trying out Firefox OS simulator and reporting bugs!  This is very very helpful to us, and we appreciate it!  Let me investigate these issues:
1. Duplicate of #284 
2. This was one of our oldest bugs #7 and was just fixed in #305 .  Go to about:addons and double check that your version is at least 3.0pre2.  If it's not, remove it (from that menu), then reinstall from the link in the README.  Looks like you were running [Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi).
3. type=datetime-local and type=datetime, might be a platform issue, will investigate later.
4. Verified

**Comment by mykmelez** [comment] 2013-03-29 21:13
The third issue is #218, which I just reopened, now that we have more information and are able to confirm the problem!

I can reproduce the fourth issue as well, but it isn't yet clear to me exactly what we should be doing about it, since I'm not sure how those buttons affect the ability for app developers to test their apps in the Simulator. If we do find that one or more of the buttons is important for app developers for some particular reason, then let's open a new issue to fix the button(s) for that specific reason.

In the meantime, I'm going to close this issue, as all of the specific problems we've identified here are addressed by other issues or aren't actually issues in the Simulator, so there aren't any specific problems to track here.

**Closed as completed by mykmelez** 2013-03-29 21:13 UTC
