### ISSUE TITLE
Script execution scope

### ISSUE THREAD

**Issue by Sco768** [mozilla/r2d2b2g#209] opened 2012-12-13 15:16 UTC
Windows 7 x64 with FF 17.0.1 x86.

Since some sites like http://www.screenresolution.org/ and http://internet.yandex.ru report my screen resolution as 1920x1280, I believe javascript is not scoped to emulator only. That seems broken if not insecure.

**Comment by rpl** [comment] 2012-12-13 20:05
This can be related to limitations in the screen resolution emulation code currently used in the b2g-desktop builds.

**Comment by digitarald** [comment] 2012-12-19 00:52
Duplicate of #7.

**Closed as completed by digitarald** 2012-12-19 00:52 UTC
