### ISSUE TITLE
Impossible to install the"popular" app in the market

### ISSUE THREAD

**Issue by stefanostatuti** [mozilla/r2d2b2g#603] opened 2013-06-11 21:36 UTC
hi 
i can't install the "popular" app  in the store, if i click on Wikipedia's app (the blu button) does not happen nothing (no error, log is clean :|), i can't open the detailed tab of wikipedia.
other apps (for example Pasjans/solitaire) if i click on Free blu button on popular tab I have the same effect I had with wiki. but now i can install the app opening the detailed tab.

**Comment by mykmelez** [comment] 2013-06-13 22:55
I can reproduce this problem consistently, but it doesn't occur in 3.0.1, so it seems to be a regression, probably from the touch event helper landing.

Steps To Reproduce:
1. open Marketplace app;
2. scroll down list of Popular apps to Wikipedia;
3. press Free button in Wikipedia entry.

Expected Results: I am prompted to install Wikipedia app.
Actual Results: I am not prompted to install Wikipedia app.

I've also experienced other strange behavior that is probably related. For example, when I click the Wikipedia Free button twice, then the Pasjans/Solitaire Free button, and then the Twitter Free button, one of two things happens:
1. I am prompted to install Wikipedia;
2. the SoundCloud Details page appears.

Neither result is expected!

@ochameau, the logs are consistent for both succeeding and failing clicks, but they include a second sequence of mouse events that includes a mousemove each time I click the mouse button:

```
info: r2d2b2g: desktop-helper (TouchEventHandler): mousedown:
info: r2d2b2g: desktop-helper (TouchEventHandler): mouseup: 1
info: r2d2b2g: desktop-helper (TouchEventHandler): click
desktop-helper (TouchEventHandler): click: fire
info: r2d2b2g: desktop-helper (TouchEventHandler): mousedown: fire
info: r2d2b2g: desktop-helper (TouchEventHandler): mousemove: fire
info: r2d2b2g: desktop-helper (TouchEventHandler): mouseup: fire
```

So it seems like the touch event helper correctly observes the mousedown/mouseup sequence and turns it into a click event, but then it observes another (nonexistent) mousedown/mousemove/mouseup sequence. Perhaps that second sequence is causing trouble?

**Comment by mykmelez** [comment] 2013-06-14 18:54
@ochameau Can you take this one on?

**Comment by ochameau** [comment] 2013-06-14 23:49
It looks like there is some issue with touch and scrollable elements.
Some simple modification to touch-event code like this https://github.com/ochameau/gaia/commit/125fedddcc92e31776f693cc5f128585c6167ce9 seems to fix this issue.

I'll submit a gaia bug/patch on Monday and try to see if there is other similar issue in this code.
In the meantine, you can cherry pick this fix (this branch is against gaia master) if there is still a chance to pick it for this week preview.

**Comment by mykmelez** [comment] 2013-06-14 23:51
I pushed this week's preview on Wednesday! But there's still time for it to make next week's preview!

**Comment by mykmelez** [comment] 2013-06-15 01:25
(And I'm happy to cherry-pick the fix if necessary to get it into next week's preview build.)

**Comment by ochameau** [comment] 2013-06-17 13:35
I opened a gaia bug: https://bugzilla.mozilla.org/show_bug.cgi?id=883834

**Comment by mykmelez** [comment] 2013-06-20 19:33
I cherry-picked https://github.com/mykmelez/gaia/commit/f2e1981e5ac09b72e1e8ffcbc0f5f6c42cb92037 to a [v1-train-integration branch](https://github.com/mykmelez/gaia/tree/v1-train-integration) in the mykmelez/gaia repository that the Simulator uses to build Gaia, then I updated Gaia to that branch, so this is now fixed, and the fix is in the latest preview build ([Windows](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-windows.xpi), [Mac](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-mac.xpi), [Linux](https://ftp.mozilla.org/pub/mozilla.org/labs/r2d2b2g/r2d2b2g-linux.xpi)).

I still have trouble when I click after I drag. Most of the time, that click is ignored, although a followup click is observed; but at least the clicks that are observed are in the correct position.

**Closed as completed by mykmelez** 2013-06-20 19:33 UTC
Labels: bug
