### ISSUE TITLE
When appcache fails to resolve, the installation fails silently (simulator only)

### ISSUE THREAD

**Issue by mattbasta** [mozilla/r2d2b2g#306] opened 2013-02-11 19:17 UTC
If the "appcache_path" of the manifest points to an invalid appcache or an appcache which does not resolve (i.e.: a non-200 response), Firefox OS would otherwise throw an error. In the simulator, this error does not appear and the app installation silently fails.

**Comment by nickdesaulniers** [comment] 2013-02-25 17:27
This may be because the simulator doesn't always have the latest builds of B2G and Gaia, so it wouldn't surprise me if we just happened to take a snapshot during a regression.  In the meanwhile, can you push a dummy branch of the app you were testing with the bad appcache and link it here, for testing?

**Comment by mattbasta** [comment] 2013-02-25 18:38
You can just use something like this:

http://badappcache.testmanifest.com/manifest.webapp

**Comment by mykmelez** [comment] 2013-05-17 17:06
Fixed by #523.

**Closed as completed by mykmelez** 2013-05-17 17:06 UTC
Labels: bug
