### ISSUE TITLE
Doesn't show up in the Tools menu with Nightly as of 2013-05-14

### ISSUE THREAD

**Issue by mcepl** [mozilla/r2d2b2g#520] opened 2013-05-14 00:33 UTC
I have freshly upgraded to 0.3 version from AMO, and now I cannot start the emulator, because it is not present in the Tools/Web DEveloper/ menu.
![screenshot from 2013-05-14 02 31 17](https://f.cloud.github.com/assets/198999/499119/cf21df16-bc2d-11e2-9e73-b53403e312e3.png)

**Comment by xantares** [comment] 2013-05-14 16:16
Same here with latest stable and latest emulator plugin version.

**Comment by mykmelez** [comment] 2013-05-14 20:13
This sounds like a duplicate of #518.

**Closed as completed by mykmelez** 2013-05-14 20:13 UTC
