### ISSUE TITLE
Blank screen when Simulator launches

### ISSUE THREAD

**Issue by dangoor** [mozilla/r2d2b2g#131] opened 2012-11-19 16:14 UTC
There have been two reports on the [Hacks post](https://hacks.mozilla.org/2012/11/announcing-the-prototype-firefox-os-simulator/) today of people getting a blank screen when they launch the Simulator. One each from Mac and Windows, so it doesn't appear to be a platform specific problem.

I haven't seen this personally and I just discovered that the Simulator uses its own profile that is not tied to the Firefox profile at all so it's harder for me to test from a clean slate.

**Comment by alastaircoote** [comment] 2012-11-19 16:31
I am one of the people that is seeing this, on a MB Pro, OSX 10.8.2.

The log shows the following:
- Unknown property '-moz-align-self'
- OpenGL LayerManager Initialized Successfully
- OpenGL LayerManager Initialized Successfully

...and then nothing. Interestingly, when I right-clicked on the console to copy and paste these errors I got an instant crash, with [this trace](http://pastebin.com/Cj1AME2m).

**Comment by fwenzel** [comment] 2012-11-19 17:19
Crash on right-clicking the console is reproducible for me also, likely to be unrelated to the "blank screen" issue.

**Comment by dvenkatas** [comment] 2012-11-20 05:18
I am also seeing the same. I am on Windows 7 / with SP installed

Firefox : 16.0.2

**Comment by HerrKauwer** [comment] 2012-11-20 08:12
I found out what's happening: I'm running something on port 9999. If I close that it suddenly works ;)

**Comment by alastaircoote** [comment] 2012-11-20 20:52
Looks like that is my problem too. D'oh!

**Comment by mykmelez** [comment] 2012-11-27 02:04
Fixed by the pull request, which disables the obsolete listener on port 9999.

**Closed as completed** 2012-11-27 02:04 UTC
